CHANGELOG.md, demo/src/index.html, docs/demos/index.html, docs/demos/spatial.html, docs/demos/tsne.html, docs/index.html
=> Google analytics everywhere [skip ci]

cypress/integration/vitessce.spec.js, src/components/heatmap/HeatmapCellColorCanvas.js, src/components/heatmap/HeatmapCellSelectionCanvas.js, src/components/heatmap/HeatmapDataCanvas.js, src/components/heatmap/utils.js
=> Clean up canvas methods... not really that much copy/paste

CHANGELOG.md, src/css/index.css
=> Fix scrollbars

CHANGELOG.md, README.md, demos.md, push-demo.sh
Changes in wording and organization that should make the development process for this repo more clear.
=> Suggestions from Jennifer

src/app/api.js, src/components/scatterplot/Scatterplot.js
=> Deck.gl view offset becomes target, update initial target values

CHANGELOG.md, src/components/cell-tooltip/CellTooltip.js, src/components/cell-tooltip/CellTooltipText.js, src/css/index.css
This pull request contains a component called `CellTooltipText` that displays the contents of the cell's `factors` json object as a two-row table.
=> Status tooltip

.eslintrc.yml, .travis.yml, docz-template.html, error.html, package.json, src/app/componentRegistry.js, src/components/layermanager/LayerManagerPublisher.js, src/components/spatial/Spatial.js, src/schemas/cells.schema.json, src/schemas/clusters.schema.json, src/schemas/dataset.schema.json, src/schemas/factors.schema.json, src/schemas/genes.schema.json, src/schemas/images.schema.json, src/schemas/molecules.schema.json, src/schemas/neighborhoods.schema.json, src/schemas/schema.mdx, src/vendor/OpenSeadragonComponent.js
Now that the repo is moved, update all the links.
Finish fix #260.
=> hms-dbmi -> hubmapconsortium

src/components/layermanager/LayerManagerPublisher.js
Arrow in message was confusing; There was no confirmation when we got the last layer
=> Helpful layer loading log message

README.md
As new users/developers, is there other information you would have liked to see on the readme?
=> include architecture diagram

src/components/scatterplot/Scatterplot.js, src/components/spatial/Spatial.js, src/components/utils.js
=> Keep consistent references across layer initializations to speed diffing

nwb.config.js
Sort of a policy question, but does it seem reasonable to you to say that UMD is just not a preferred format?
=> No UMD. Fix #297

cypress/integration/vitessce.spec.js, src/app/api.js
Or maybe it should be author-year? What would make the most sense to you, coming from outside?
=> Just author names

src/components/cell-tooltip/CellTooltip1DVertical.js, src/components/cell-tooltip/CellTooltip2D.js, src/components/cell-tooltip/CellTooltipText.js
=> Cell ID in tooltip

src/app/Welcome.js, src/app/api.js, src/app/componentRegistry.js, src/components/TitleInfo.js, src/components/cell-tooltip/CellTooltipText.js, src/components/classNames.js, src/components/factors/Factors.js, src/components/genes/Genes.js, src/components/status/Status.js, src/components/status/Status.test.js, src/css/component.scss, src/css/controls.scss, src/css/index.scss, src/css/radio.scss, src/css/tooltips.scss
Undoes this commit https://github.com/hubmapconsortium/vitessce/commit/ae973182c005f0294794a8518827b3a73471bbe0
=> Un-css-module. Fixes #323

src/components/cell-tooltip/CellTooltip2D.js
I believe this was a request a few weeks back by either Nils or Peter
=> Full width and height crosshair

src/components/sets/SetsManagerTab.js, src/components/sets/sets.js, src/components/sets/sets.test.js
Still does not fix the css/offset issue with Firefox. Just makes the dragging behavior more predictable.
=> Improve dragging and add tests

src/layers/SelectionLayer.js
=> Rect selection click outside bugfix

src/components/sets/sets-manager.scss
=> Fixed sets tabs

CHANGELOG.md
Please add anything else you think is important. Thanks!
=> Add recent work to change log

CHANGELOG.md, src/schemas/cells.schema.json
Alternatively:
- There could be no required fields,
- or I could supply an empty genes and factors list in my data.
Thoughts? Will need to make a new NPM release, tomorrow at latest. Anything else that needs to be wrapped up?
=> Only require "mappings"

.eslintrc.yml, CHANGELOG.md, src/app/app.js, src/schemas/cells.schema.json
(Sorry: I didn't start this from master. I can rebase it, if needed.)
Until #241 is addressed, this provides an easy way for developers to get viewconfs.
I'll fix the linting...
=> dump viewconf to log

CHANGELOG.md, src/app/api.js, src/components/scatterplot/Scatterplot.js, src/components/scatterplot/ScatterplotSubscriber.js
When I went to push a scatterplot in the portal, the please-wait never cleared. I recreated the problem here, and fixed it... but this is one of the parts of the architecture that has felt sketchy to me. I think for now, we just want to fix it... but if a better long-term solution is at the back of your mind, I'd be glad to hear it.
=> scatter should notify when cells consumed

CHANGELOG.md, src/components/layerpublisher/LayerPublisher.js
Fix #449, but not tested... I was adding more exports, and I didn't get the mocks working correctly. I'll make another PR to improve the cypress coverage of error handling, and that might be considered first.
=> Check that HTTP status is good

src/app/Welcome.js, src/components/AbstractSelectableComponent.js, src/components/TitleInfo.js, src/components/cell-tooltip/CellTooltip2D.js, src/components/factors/Factors.js, src/components/genes/Genes.js, src/components/heatmap/Heatmap.js, src/components/sets/Popover.js, src/components/sets/TreeNode.js, src/components/sourcepublisher/SourcePublisher.js, src/schemas/PrettyJsonSchema.js
=> Use shorthand react fragment syntax

CHANGELOG.md, src/components/heatmap/utils.js, src/components/utils.js
=> Add default cell info values

CHANGELOG.md, src/layers/SelectionLayer.js
=> Change rectangle selection to dragging

CHANGELOG.md, src/layers/SelectionLayer.js
=> Clear rectangle or lasso selection on click

CHANGELOG.md, package-lock.json, package.json
- Upgrade viv and vitessce-grid
- Make react/react-dom peer deps
=> Upgrade Deps

CHANGELOG.md, README.md
=> Update README release instructions

CHANGELOG.md, src/components/layer-controller/ImageAddButton.js
Fixes #557.  This isn't in place of a more robust solution for handling the a potential multi-dataset use-case, but this is an easy win in the mean time.
=> Fix Scrollable Image Layers

CHANGELOG.md, src/components/layer-controller/ImageAddButton.js, src/css/_channels.scss, src/css/index.scss
Adds a dark border on the light theme for the Add Image Layer button
=> Button theme

CHANGELOG.md, src/components/layer-controller/reducer.js
Hopefully this resolves #589.  I built the branch locally in production and tried it, and it seems to work.
=> Resolve channels bug.

CHANGELOG.md, TESTING.md
Does this sound good to everyone?  I think with #607, #605, and #600 , all outstanding Safari bugs have been resolved, so we should be able to make sure that Safari is supported going forward.
=> Testing docs

CHANGELOG.md, src/components/description/DescriptionSubscriber.js, src/components/heatmap/utils.js, src/components/layer-controller/LayerControllerSubscriber.js, src/components/sets/CellSetsManagerSubscriber.js, src/components/sets/reducer.js, src/components/sourcepublisher/SourcePublisher.js, src/components/spatial/Spatial.js, src/components/spatial/SpatialSubscriber.js, src/components/spatial/spatial.test.js, src/events.js
Ok trying this again. It was unclear which of the branches you were using. This is the one with useMemo. I have commented out the one problematic Spatial test
=> Multiple sources (with useMemo change in Spatial)

CHANGELOG.md, src/schemas/cells.schema.json, src/schemas/fixtures/genes.bad.message.json, src/schemas/genes.schema.json
If you go to https://portal.hubmapconsortium.org/browse/dataset/93fa2d788eb7315cc8b4edf84eb919e0#files you'll see that the schema validation fails.  This allows the validation to pass.
=> Change genes schema integer to float values

CHANGELOG.md, src/components/layer-controller/LayerControllerSubscriber.js
=> Fix Names and Booleans

CHANGELOG.md, src/app/api.js
Corresponding PR: https://github.com/hubmapconsortium/vitessce-data/pull/107
=> Bump vitessce-data version

CHANGELOG.md, src/components/layer-controller/LayerControllerSubscriber.js
Noticed this while updating #648.  On that branch (or master) you just need to resize the `linnarsson` dataset and more channels appear.
=> Fix resizing bug.

CHANGELOG.md, src/app/PubSubVitessceGrid.js, src/components/layer-controller/LayerControllerSubscriber.js, src/components/layer-controller/RasterLayerController.js, src/components/layer-controller/VectorLayerController.js, src/components/layer-controller/styles.js, src/css/_app.scss, src/css/_bootstrap-minimal.scss, src/css/_channels.scss
This should fix #634.  Any comments are welcome.
=> Update Spacing on Layer Controller

CHANGELOG.md, cypress/integration/vitessce.spec.js, src/app/PubSubVitessceGrid.js, src/components/sourcepublisher/SourcePublisher.js, src/css/_app.scss
This changes the Please wait modal to an animated spinner in the center of the window.
=> Change please wait modal to spinner

CHANGELOG.md, src/components/heatmap/HeatmapSubscriber.js
=> Fix heatmap bug

CHANGELOG.md, src/components/spatial/SpatialSubscriber.js
I misplaced a boolean while refactoring a bit: https://github.com/hubmapconsortium/vitessce/pull/653/commits/681e6e6ea35b8e6ba16ebca435ababf8ebaf0c18
=> Filter zarr.

CHANGELOG.md, src/components/TitleInfo.js
Addresses the first two points in #681.  The last point is thorny because the imaging data can have multiple different files.
=> Download Button Fixes

CHANGELOG.md, package-lock.json, package.json
Towards https://github.com/hubmapconsortium/portal-ui/issues/977.
=> Upgrade Viv to 0.3.3

CHANGELOG.md, src/components/spatial/SpatialSubscriber.js, src/components/spatial/utils.js
=> Dont display zero counts

CHANGELOG.md, package-lock.json, package.json, src/components/layer-controller/LayerControllerSubscriber.js, src/components/layer-controller/RasterLayerController.js, src/components/layer-controller/reducer.js, src/components/spatial/Spatial.js
This adds a feature I implemented for Avivator (auto-sliders) and upgrades us to the new package/location
=> Add auto-sliders and upgrade.

CHANGELOG.md, src/components/layer-controller/RasterLayerController.js
=> Fix Channel Selection Bug 

src/components/data-hooks.js, src/components/sets/CellSetsManagerSubscriber.js, src/components/spatial/SpatialSubscriber.js
Here I added a `dataset` key to the auto cell set selections as well. (This is a PR into the other branch)
=> Auto layers async bug addition

CHANGELOG.md, package-lock.json, package.json, src/app/export-utils.js, src/app/export-utils.test.js, src/app/index.js, src/index.js
As per our discussion last week in the Vitessce meeting to bring this functionality within Vitessce.
=> Add encode/decode URL functions

CHANGELOG.md, src/components/data-hooks.js, src/components/layer-controller/ChannelController.js, src/components/layer-controller/ImageAddButton.js, src/components/layer-controller/LayerControllerSubscriber.js, src/components/layer-controller/LayerOptions.js, src/components/layer-controller/RasterLayerController.js, src/components/layer-controller/VectorLayerController.js, src/components/spatial/Spatial.js, src/components/spatial/constants.js, src/components/spatial/utils.js, src/schemas/config.schema.json
Fixes an issue that Tiffany had with sharing state and a given domain type.
=> Add domain type to view config

CHANGELOG.md, src/components/layer-controller/LayerControllerSubscriber.js
We should not require raster data for the Layer Controller.
=> Fix Raster Being Required for Layer Controller

CHANGELOG.md, src/components/genes/Genes.js, src/css/_genes.scss, src/css/index.scss
This implements a basic search function within the Genes component using substring matching.  I think this will be useful for long, repetitive genes names that differ by an id (like in the Satija example). Fixes #645.
=> Searchable Genes List

CHANGELOG.md, package-lock.json, package.json, src/components/higlass/HiGlassSubscriber.js
=> Dynamic lazy package versions and environment mode

CHANGELOG.md, test.sh
Fixes the failing run: https://github.com/vitessce/vitessce/runs/1619665930
=> Fix test.sh

CHANGELOG.md, package-lock.json, package.json
Fixes a small bug with opacity.  Slacking you the test demo.
=> Upgrade Viv To 0.8.2

CHANGELOG.md, src/loaders/anndata-loaders/CellsZarrLoader.js
This PR fixes a bug which causes the `cells` data from `anndata-cells.zarr` files to load infinitely when a `"factors"` option is not present.
Test view config ([localhost demo](http://localhost:3000/?url=data:,{%22version%22:%20%221.0.0%22,%22name%22:%20%2210x%20visium%20human%20lymph%20node%22,%22initStrategy%22:%20%22auto%22,%22datasets%22:%20[{%22uid%22:%20%22visium%22,%22files%22:%20[{%22type%22:%20%22expression-matrix%22,%22fileType%22:%20%22anndata-expression-matrix.zarr%22,%22url%22:%20%22https://s3.amazonaws.com/vitessce-data/0.0.32/master_release/human_lymph_node_10x/human_lymph_node_10x.h5ad.zarr%22,%22options%22:%20{%22matrix%22:%20%22obsm/X_hvg%22,%22geneFilter%22:%20%22var/highly_variable%22}},{%22type%22:%20%22cells%22,%22fileType%22:%20%22anndata-cells.zarr%22,%22url%22:%20 …
=> Fix factors bug

CHANGELOG.md, src/app/Welcome.js, src/app/app.js, src/css/_app.scss, src/demo/index.js
This PR only contains the banner with a link to the beta site.
Ultimately we will want to merge #810 as well, but it is a huge PR, and we do not want to rush the review process.
=> Beta docs site banner

CHANGELOG.md, src/components/sets/CellSetExpressionPlotSubscriber.js
=> Add Gene Name to Violin Plot.

CHANGELOG.md, src/app/Vitessce.js, src/app/styles.js, src/components/layer-controller/ChannelController.js, src/components/layer-controller/LayerOptions.js, src/components/layer-controller/VectorLayerController.js, src/components/layer-controller/styles.js, src/components/shared-plot-options/CellColorEncodingOption.js
Fixes #833 and fixes #861
No rush on this.  Should we open a separate issue for the smaller styling in notebooks or is that intentional?  It doesn't look bad, just curious
=> Fix MUI Height for `Checkbox` in `LayerController`

CHANGELOG.md, src/loaders/RasterJsonLoader.js
=> Cache Initial `raster.json` Channel Settings Load

CHANGELOG.md, src/app/Vitessce.js, src/app/styles.js, src/components/layer-controller/ChannelController.js, src/components/layer-controller/LayerOptions.js, src/components/layer-controller/VectorLayerController.js, src/components/layer-controller/styles.js, src/components/shared-plot-options/CellColorEncodingOption.js
This reverts commit 33f210da0ea09cc3e7687e67fd6ddf7ae3e3518a.
=> Revert "Fix MUI Height for `Checkbox` in `LayerController` (#903)"

CHANGELOG.md, src/components/sets/CellSetSizesPlotSubscriber.js, src/components/sets/hooks.js
Fixes https://github.com/hubmapconsortium/portal-ui/issues/1731
=> Fix `cellSetColor` Bug from Portal

CHANGELOG.md, src/components/sets/cell-set-utils.js, src/components/sets/hooks.js
This should be much faster [(example)](http://localhost:3000/?url=data%3A%2C%7B+++%22version%22%3A+%221.0.0%22%2C+++%22name%22%3A+%223ac0768d61c6c84f0ec59d766e123e05%22%2C+++%22datasets%22%3A+%5B+++++%7B+++++++%22uid%22%3A+%2240334a99-2be7-4904-bc75-102609fe53e9%22%2C+++++++%22name%22%3A+%2240334a99-2be7-4904-bc75-102609fe53e9%22%2C+++++++%22files%22%3A+%5B+++++++++%7B+++++++++++%22type%22%3A+%22cells%22%2C+++++++++++%22fileType%22%3A+%22anndata-cells.zarr%22%2C+++++++++++%22url%22%3A+%22https%3A%2F%2Fvitessce-demo-data.storage.googleapis.com%2Fanndata-test%2FSingle_cell_drug_screening_a549-42-remixed_chunked.zarr%22%2C+++++++++++%22options%22%3A+%7B+++++++++++++%22mappings%22%3A+%7B+%22UMAP%22%3A+%7B+%22key%22%3A+%22obsm%2FX_umap%22%2C+%22dims%22%3A+%5B0%2C+1%5D+%7D+%7D%2C+++++++++++++%22 …
=> Boost Performance of Violin Plot

CHANGELOG.md, src/components/shared-spatial-scatterplot/ToolMenu.js
Bug caught by Nils on Slack.  Previously, 0's displayed where there should have been nothing.
=> Fix 0's Displaying Where Selection Tools Were

CHANGELOG.md, src/components/layer-controller/LayerOptions.js
=> Fix 3D Dropdown for 2D-only

CHANGELOG.md, src/components/hooks.js, src/components/layer-controller/LayerControllerSubscriber.js, src/components/layer-controller/LayerOptions.js
=> Use Vitessce Component Height for Determining 3D/2D Sizing.

CHANGELOG.md, src/components/spatial/Spatial.js
=> Fix Empty Cell Set Selection in Bitmask Bug

CHANGELOG.md, README.md
See https://github.com/vitessce/vitessce/pull/1007#issuecomment-889294618
=> Update README About Use With (Remote) View Configs

.eslintrc.yml, CHANGELOG.md, README.md, error.html, package.json, src/app/Welcome.js, src/components/layer-controller/LayerOptions.js, src/components/sets/HelpTooltip.js, src/css/_heatmap.scss, src/layers/heatmap-bitmap-layer-shaders.js, src/schemas/cell-sets-tabular.schema.json, src/schemas/cell-sets.schema.json, src/schemas/cells.schema.json, src/schemas/clusters.schema.json, src/schemas/config-0.1.0.schema.json, src/schemas/config-1.0.0.schema.json, src/schemas/config-1.0.1.schema.json, src/schemas/config-1.0.2.schema.json, src/schemas/config-1.0.3.schema.json, src/schemas/genes.schema.json, src/schemas/molecules.schema.json, src/schemas/neighborhoods.schema.json, src/schemas/raster.schema.json, test.sh
Follow up from https://github.com/vitessce/vitessce/pull/1012#issuecomment-894380666
=> Replace "hubmapconsortium/vitessce" with "vitessce/vitessce"

CHANGELOG.md, src/components/data-hooks.js, src/components/description/DescriptionSubscriber.js, src/components/genes/ExpressionHistogramSubscriber.js, src/components/genes/GenesSubscriber.js, src/components/heatmap/HeatmapSubscriber.js, src/components/higlass/GenomicProfilesSubscriber.js, src/components/higlass/HiGlassSubscriber.js, src/components/hooks.js, src/components/layer-controller/LayerControllerSubscriber.js, src/components/scatterplot/ScatterplotSubscriber.js, src/components/sets/CellSetExpressionPlotSubscriber.js, src/components/sets/CellSetSizesPlotSubscriber.js, src/components/sets/CellSetsManagerSubscriber.js, src/components/spatial/SpatialSubscriber.js
Fixes something that came up in discussion today.
=> Loading Callbacks for Gene Selection

CHANGELOG.md, src/components/layer-controller/LayerController.js, src/components/layer-controller/LayerOptions.js, src/components/layer-controller/utils.js
Mirroring https://github.com/hms-dbmi/viv/pull/495 here
=> Better Handling of Large Thin Volumes

CHANGELOG.md, src/components/layer-controller/LayerController.js
=> Fix Channel Consistency Issue with High Load Times

CHANGELOG.md, src/components/shared-spatial-scatterplot/AbstractSpatialOrScatterplot.js
Fixes https://github.com/hms-dbmi/viv/issues/511 here.
- Use correct picking information for cell highlighting in `bitmask`
=> Fix `bitmask` picking

CHANGELOG.md, package-lock.json, package.json, scripts/webpack.config-common.js, src/app/state/hooks.js, src/components/layer-controller/LayerController.js, src/components/layer-controller/RasterChannelController.js, src/components/layer-controller/utils.js, src/components/spatial/Spatial.js, src/layers/BitmaskLayer.js, src/layers/bitmask-layer-shaders.js
- Upgrade `Viv`
- Add babel plugin likely needed because we upgraded `Viv`'s bundling:  https://github.com/hms-dbmi/viv/pull/506
=> Upgrade `Viv` to 0.11.0

CHANGELOG.md, src/components/TitleInfo.js, src/components/classNames.js, src/components/hooks.js, src/components/layer-controller/ChannelOptions.js, src/components/layer-controller/ImageAddButton.js, src/components/sets/HelpTooltip.js, src/components/shared-mui/components.js, src/components/shared-mui/styles.js, src/css/_app.scss
Fixes #1079 
Fixes #394 
- Move ClickAwayListener inside Popper (https://stackoverflow.com/questions/55143914/material-ui-clickawaylistener-close-when-clicking-itself)
- Refactor TitleInfo component CSS
=> Fix popper menu

CHANGELOG.md, src/components/scatterplot/Scatterplot.js, src/components/spatial/Spatial.js, src/layer-extensions/ScaledExpressionExtension/ScaledExpressionExtension.js
Fixes #1078
- Make sure instanced layers get instanced (i.e the correct `divisor`) attribute
=> Fix Stroke Expression Value Display

CHANGELOG.md, src/components/heatmap/HeatmapOptions.js, src/components/layer-controller/LayerOptions.js, src/components/layer-controller/VolumeOptions.js, src/components/layer-controller/shared-channel-controls.js, src/components/layer-controller/styles.js, src/components/scatterplot/ScatterplotOptions.js, src/components/shared-plot-options/CellColorEncodingOption.js, src/components/shared-plot-options/OptionSelect.js, src/components/shared-plot-options/styles.js, src/components/spatial/SpatialOptions.js, src/css/_bootstrap-minimal.scss
I still can't reproduce, but does this fix the text cutoff issue?
=> Channel select styles

docs/docs/tutorial-visium.mdx
Hey, was just looking through the tutorial and noticed a small issue.
Scanpy has been distributed on conga-forge (replacing bioconda) since version 1.7.2
- Fix install instructions for scanpy
Scanpy has been distributed on conga-forge (replacing bioconda) since version 1.7.2
=> Update scanpy install instructions

CHANGELOG.md, docs/docs/data-file-types.mdx, docs/docs/introduction.md, docs/docs/platforms.md, docs/docs/view-config-js.md, docs/docs/view-config-json.md, docs/docusaurus.config.js
=> Update R package URLs

CHANGELOG.md, package-lock.json, package.json
Fixes #1172 
- Upgrade Viv to 0.12.6
=> Upgrade Viv to 0.12.6

CHANGELOG.md, src/components/layer-controller/RasterChannelController.js
Fixes #
- Prevent setting a slider `value` outside the `min`, `max` range, which results in a MUI error and crashed page.
=> Fix channel slider bug

CHANGELOG.md, docs/docs/tutorial-gh-pages.mdx, docs/sidebars.js
This tutorial walks through creating a new React app with a Vitessce dependency, configuring the Vitessce react component via a view config, and deploying the app to GitHub pages using a GitHub action.
=> Add tutorial describing how to deploy to GitHub Pages

CHANGELOG.md, src/components/scatterplot/Scatterplot.js, src/components/spatial/Spatial.js
=> Fix Molecules

CHANGELOG.md, package-lock.json, package.json
Merged non-docs dependabot PRs using https://github.com/rnorth/gh-combine-prs
```sh
gh extension install rnorth/gh-combine-prs
gh combine-prs --query "author:app/dependabot NOT /docs in:title NOT react-dev-utils in:title NOT karma in:title" --skip-pr-check
```
=> Combined dependabot updates

CHANGELOG.md, README.md
Add more lab meeting and other presentation links to the README
=> Add presentation links to README

CHANGELOG.md, docs/docs/data-troubleshooting.md, docs/sidebars.js
Related to https://github.com/vitessce/vitessce/issues/1167
=> Add data troubleshooting docs page

.github/workflows/deploy.yml, .github/workflows/test.yml, CHANGELOG.md, create-release.sh, docs/docs/data-file-types.mdx, docs/docs/dev-add-component.md, docs/docs/view-config-json.md, docs/docusaurus.config.js, src/schemas/schema-schema.sh, test.sh
=> Rename default branch

CHANGELOG.md, docs/docs/view-config-json.md, src/app/state/hooks.js, src/app/view-config-upgraders.js, src/app/view-config-utils.js, src/app/view-config-utils.test.fixtures.js, src/app/view-config-utils.test.js, src/app/view-config-versions.js, src/app/vitessce-grid-layout/VitessceGridLayout.js, src/app/vitessce-grid-layout/VitessceGridLayout.test.js, src/app/vitessce-grid-layout/layout-utils.js, src/app/vitessce-grid-layout/layout-utils.test.js, src/schemas/config-1.0.10.schema.json, src/schemas/config-1.0.10.schema.test.js
[PR diagram](https://docs.google.com/drawings/d/1gCFPt9yA5R-BxAToZYcD_Cf_QYzYoCpYr25ZAeA5XBY/edit)
Fixes #858
=> Optional view `uid` property

CHANGELOG.md, docs/docs/constants.mdx, docs/docs/tutorial-visium.mdx, docs/docs/view-config-js.md, docs/src/pages/_ViewConfigTabs.js, docs/src/pages/_live-editor-examples.js, src/api/VitessceConfig.js, src/api/VitessceConfig.test.js, src/demo/view-configs/codeluppi.js, src/demo/view-configs/eng.js, src/demo/view-configs/hubmap.js
[PR diagram](https://docs.google.com/drawings/d/1gCFPt9yA5R-BxAToZYcD_Cf_QYzYoCpYr25ZAeA5XBY/edit)
Fixes #1225 
- Add the required `schemaVersion` parameter for the `VitessceConfig` constructor. Since this is a breaking change, the next version bump should be a major version (v2.0.0).
=> Add schemaVersion parameter

CHANGELOG.md, src/components/sets/CellSetsManagerSubscriber.js
=> Remove cellSets requirement

CHANGELOG.md, docs/docs/js-react-vitessce.md, package-lock.json, package.json, src/app/Vitessce.js, src/app/VitessceGrid.js, src/app/vitessce-grid-layout/VitessceGridLayout.js
Fixes #1285 (partially)
- Added the optional `isBounded` property to the `Vitessce` React component that prevents users from dragging or resizing components beyond the original grid boundary.
=> Adds isBounded to Vitessce React component.

CHANGELOG.md, package-lock.json, src/components/heatmap/Heatmap.test.js
=> Fix package-lock

.github/workflows/deploy.yml, CHANGELOG.md, set-node-options.sh, test.sh
https://github.com/vitessce/vitessce/pull/1320 did not work. Trying again.
=> Update deployment scripts

src/components/heatmap/Heatmap.js
PR into https://github.com/vitessce/vitessce/pull/1151 branch
=> Add shouldUsePaddedImplementation function

CHANGELOG.md, README.md
- Adds to the deployment section of the README about that format of URL that `./copy-dev.sh` and `./copy-docs.sh` are expecting
=> Add to deployment instructions

CHANGELOG.md, package.json, packages/icons/package.json, packages/main/dev/package.json, packages/main/prod/package.json, pnpm-lock.yaml, sites/demo/package.json
=> Try bumping plugin-react

CHANGELOG.md, sites/demo/src/vitessce-demo.jsx
- Fixes issue that the list of demos does not scroll
=> Fix development demo list CSS

CHANGELOG.md, packages/main/all/src/index.js, packages/vit-s/src/index.js
=> Add plugin registration function exports

CHANGELOG.md, packages/utils/spatial-utils/src/index.js, packages/view-types/spatial/src/Spatial.js
Fixes #1318
- Pass `visible` prop to interleaved RGB layer
=> (fix): interleaved rgb visibility

CHANGELOG.md, sites/docs/docs/view-config-json.mdx
Fixes #1384 
Not sure what the underlying issue is though
=> Temporary fix for docs

CHANGELOG.md, examples/configs/src/view-configs/blin.js, packages/file-types/ome-tiff/src/OmeTiffAsObsSegmentationsLoader.js, packages/file-types/ome-tiff/src/OmeTiffLoader.js, packages/file-types/zarr/src/ome-loaders/OmeZarrLoader.js, packages/utils/spatial-utils/src/index.js, packages/utils/spatial-utils/src/spatial.js, packages/vit-s/src/file-options-schemas.js, packages/vit-s/src/index.js
=> coordinateTransformations options for image.ome-tiff and image.ome-zarr

CHANGELOG.md, README.md
Adds note about branch naming convention to README
=> Add note about branch naming to README

CHANGELOG.md, packages/view-types/heatmap/src/Heatmap.js, packages/view-types/heatmap/src/HeatmapSubscriber.js
=> Implemented clickable heatmap

CHANGELOG.md, README.md
=> Add note about pull requests to README

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, CHANGELOG.md
=> Update issue templates

.meta-updater/main.mjs, CHANGELOG.md, packages/gl/package.json, packages/utils/spatial-utils/src/spatial.js, packages/view-types/spatial/src/SpatialSubscriber.js, packages/view-types/spatial/src/utils.js, pnpm-lock.yaml
Closes #1475
- Removes logic for `tsconfig.json` from the meta-updater script
Demo: https://s3.amazonaws.com/vitessce-data/demos/2023-04-13/a234ed24/index.html
=> Pull in changes from #1475, fix bug in meta-updater

CHANGELOG.md, README.md
=> Add developer troubleshooting notes

CHANGELOG.md, packages/view-types/obs-sets-manager/src/ObsSetsManagerSubscriber.js
Towards #1422 
(another independent change that was originally in https://github.com/vitessce/vitessce/pull/1441)
=> Improve cell set manager performance

CHANGELOG.md, packages/workers/rollup.config.js
(Change that I originally made in #1519 but have reverted there to make an independent PR since it was unrelated)
=> Remove dead code from rollup config

packages/vit-s/src/VitS.js, sites/html/src/animated-config.html, sites/html/src/animated-config.js
=> Keller mark/animation test

.changeset/nice-carpets-fix.md, packages/config/src/constants.js, sites/docs/docs/default-config.md, sites/docs/src/pages/_ViewConfigEditor.js, sites/docs/src/pages/styles.module.css
=> Update docs for zero-config mode hints

.changeset/orange-pens-explode.md, sites/docs/docs/view-config-json.mdx
=> Fix config.uid docs

DEMOS.md, DOCS.md
=> Demos for v3.1.1

.changeset/forty-cherries-sneeze.md, .meta-updater/main.mjs, packages/utils/other-utils/package.json, packages/utils/other-utils/src/root.js, packages/view-types/feature-list/package.json, packages/view-types/feature-list/src/FeatureListSubscriber.js, packages/view-types/heatmap/package.json, packages/view-types/heatmap/src/HeatmapSubscriber.js, packages/view-types/scatterplot-embedding/package.json, packages/view-types/scatterplot-embedding/src/EmbeddingScatterplotSubscriber.js, packages/view-types/scatterplot-gating/package.json, packages/view-types/scatterplot-gating/src/GatingScatterplotOptions.js, packages/view-types/scatterplot-gating/src/GatingSubscriber.js, packages/view-types/spatial/package.json, packages/view-types/spatial/src/utils.js, pnpm-lock.yaml
Fixes #
Pluralize supports defining custom plurals, while `plur` only falls back to a fixed list (PRs can be made via github but it is slow).
-
=> Plur to pluralize

packages/gl/src/deck.js, packages/view-types/scatterplot/src/shared-spatial-scatterplot/AbstractSpatialOrScatterplot.js, packages/view-types/spatial/package.json, packages/view-types/spatial/src/ScaleBarLayer.js, pnpm-lock.yaml
=> Nice scale bar

.changeset/yellow-goats-reflect.md, examples/configs/src/view-configs/blin.js, packages/view-types/spatial/src/SpatialSubscriber.js
=> Fix channel names bug

.changeset/cuddly-coins-trade.md, packages/schemas/src/schema-builders.ts
Fixes https://github.com/vitessce/vitessce/issues/1692
Temporary fix for issue with z.record in environments in which there are multiple copies of Zod.
=> Zod record bug workaround

.changeset/small-llamas-itch.md, pnpm-lock.yaml, sites/demo/cypress/e2e/vitessce-data-uri.spec.cy.js, sites/demo/package.json, sites/html/package.json
=> Upgrade cypress

consumer/README.md
=> Update portal-ui testing instructions

DEMOS.md, DOCS.md
=> Add demo URLs

.changeset/angry-donkeys-worry.md, packages/view-types/description/src/DescriptionSubscriber.js, packages/view-types/feature-list/src/FeatureListSubscriber.js, packages/view-types/genomic-profiles/src/GenomicProfilesSubscriber.js, packages/view-types/genomic-profiles/src/HiGlassSubscriber.js, packages/view-types/heatmap/src/HeatmapSubscriber.js, packages/view-types/layer-controller-beta/src/LayerControllerSubscriber.js, packages/view-types/layer-controller/src/LayerControllerSubscriber.js, packages/view-types/obs-sets-manager/src/ObsSetsManagerSubscriber.js, packages/view-types/scatterplot-embedding/src/EmbeddingScatterplotSubscriber.js, packages/view-types/scatterplot-gating/src/GatingSubscriber.js, packages/view-types/spatial-beta/src/SpatialSubscriber.js, packages/view-types/spatial/src/SpatialSubscriber.js, packages/view-types/statistical-plots/src/CellSetExpressionPlotSubscriber.js, packages/view-types/statistical-plots/src/CellSetSizesPlotSubscriber.js, packages/view-types/statistical-plots/src/ExpressionHistogramSubscriber.js, packages/view-types/status/src/StatusSubscriber.js, packages/vit-s/src/TitleInfo.js
=> Hide close buttons

.changeset/hip-bees-clap.md, packages/vit-s/src/TitleInfo.js
=> UseMemo for TitleInfo icon buttons

.changeset/witty-suns-doubt.md, packages/view-types/feature-list/src/FeatureListSubscriber.js, packages/view-types/genomic-profiles/src/GenomicProfilesSubscriber.js, packages/view-types/genomic-profiles/src/HiGlassSubscriber.js, packages/view-types/heatmap/src/HeatmapSubscriber.js, packages/view-types/layer-controller-beta/src/LayerControllerSubscriber.js, packages/view-types/layer-controller/src/LayerControllerSubscriber.js, packages/view-types/obs-sets-manager/src/ObsSetsManagerSubscriber.js, packages/view-types/scatterplot-embedding/src/EmbeddingScatterplotSubscriber.js, packages/view-types/scatterplot-gating/src/GatingSubscriber.js, packages/view-types/spatial-beta/src/SpatialSubscriber.js, packages/view-types/spatial/src/SpatialSubscriber.js, packages/view-types/statistical-plots/src/CellSetExpressionPlotSubscriber.js, packages/view-types/statistical-plots/src/CellSetSizesPlotSubscriber.js, packages/view-types/statistical-plots/src/ExpressionHistogramSubscriber.js, packages/vit-s/src/TitleInfo.js
=> Hide download buttons

.changeset/thin-moose-sniff.md, packages/view-types/layer-controller/src/VolumeOptions.js
=> Fix volume control text sizing issue in layerController view

.changeset/green-numbers-marry.md, packages/file-types/zarr/src/anndata-loaders/ObsSegmentationsAnndataLoader.js, packages/view-types/spatial/src/SpatialSubscriber.js, packages/vit-s/src/data-hook-utils.js, packages/vit-s/src/data-hooks.js
=> Do not include URLs in dropdowns for Zarr file types

.changeset/brown-pugs-knock.md, packages/utils/other-utils/package.json, packages/utils/other-utils/src/index.ts, packages/utils/sets-utils/src/index.js, packages/utils/sets-utils/src/interpolate-colors.js, packages/utils/sets-utils/src/interpolate-colors.test.js, packages/view-types/heatmap/src/HeatmapSubscriber.js, packages/view-types/scatterplot-embedding/src/EmbeddingScatterplotSubscriber.js, packages/view-types/scatterplot-gating/src/GatingSubscriber.js, packages/view-types/spatial-beta/src/Spatial.js, packages/view-types/spatial/src/SpatialSubscriber.js, pnpm-lock.yaml
=> Fix circular deps in pnpm workspace

.changeset/stale-dolphins-whisper.md, examples/configs/src/index.js, examples/configs/src/view-configs/multi-sample.js, packages/view-types/statistical-plots/src/CellSetExpressionPlot.js, packages/view-types/statistical-plots/src/CellSetExpressionPlotSubscriber.js
=> Add Lake et al. config

.changeset/fifty-donkeys-complain.md, packages/gl/src/heatmap-constants.js, packages/utils/other-utils/src/components.ts, packages/utils/spatial-utils/src/layer-controller.js, packages/vega/src/utils.js, packages/view-types/genomic-profiles/src/GenomicProfilesSubscriber.js, packages/view-types/layer-controller-beta/src/ChannelColorPickerMenu.js, packages/view-types/layer-controller-beta/src/ChannelVisibilityCheckbox.js, packages/vit-s/src/shared-mui/styles.js, sites/demo/src/vitessce-demo.jsx
=> light2 theme

.changeset/weak-roses-flow.md, packages/config/src/VitessceConfig.js, packages/gl/src/BitmaskLayerBeta.js, packages/schemas/src/schema-builders.ts, packages/schemas/src/view-config-versions.ts, packages/utils/other-utils/src/index.ts, packages/utils/other-utils/src/root.ts, packages/utils/spatial-utils/src/layer-controller.js, packages/vit-s/src/data-hook-utils.js, packages/vit-s/src/data-hooks-multilevel.js, packages/vit-s/src/data-hooks.js, packages/vit-s/src/hooks.js, packages/vit-s/src/state/hooks.js, packages/vit-s/src/view-config-utils.js, packages/vit-s/src/vitessce-grid-utils.js, sites/docs/docs/tutorial-plugin-file-type.mdx
=> Object.fromEntries

.changeset/curly-garlics-knock.md, packages/vit-s/src/shared-mui/styles.js, packages/vit-s/src/title-styles.js, sites/docs/src/pages/_ThemedVitessce.js
=> Update light2 theme

.changeset/nasty-pigs-suffer.md, packages/utils/other-utils/src/components.ts
=> Update un-selected color

.changeset/rare-glasses-sing.md, DEMOS.md, DOCS.md, sites/docs/docusaurus.config.js, sites/docs/plugins/monaco-editor-plugin/index.js, sites/docs/plugins/vitessce-plugin/index.js
=> Fix docs site

.changeset/stupid-sloths-sneeze.md, sites/docs/src/pages/_Index.js
=> Update beta URLs for paper

README.md
It seems that my computer was taking everything after the # as arguments:
```
❯ pnpm run build # for @vitessce/icons and @vitessce/workers
> vitessce-monorepo@3.3.9 build /Users/ilangold/Projects/Gehlenborg/vitessce
> pnpm -r build "#" "for" "@vitessce/icons" "and" "@vitessce/workers"
Scope: 46 of 47 workspace projects
packages/workers build$ rimraf ./dist/ && pnpm run build-lib "#" "for" "@vitessce/icons" "and" "@vitessce/workers"
│ > @vitessce/workers@3.3.9 build-lib /Users/ilangold/Projects/Gehlenborg/vitessce/packages/workers
│ > rollup --config rollup.config.js "#" "for" "@vitessce/icons" "and" "@vitessce/workers"
│
│ #, for, @vitessce/icons, and, @vitessce/workers → dist/index.js...
│ [!] (plugin commonjs--resolver) TypeError: The "path" argument must be of type string. Received …
```
=> (fix): install instructions

.changeset/unlucky-kiwis-switch.md, sites/docs/src/pages/_Index.js
=> MR demo redirects

.changeset/clever-mails-bake.md, sites/docs/src/pages/_Index.js
=> MR demo from query params

.changeset/ninety-tips-invite.md, sites/docs/docs/data-file-types.mdx, sites/docs/src/pages/_DataTypesTable.js
Fixes https://github.com/vitessce/vitessce/issues/1840
-
=> spatialdata.zarr file type documentation

.changeset/red-impalas-tap.md, packages/file-types/zarr/src/SpatialDataTableSource.js
=> Change tables regex

packages/view-types/spatial-three/src/GeometryAndMesh.js, packages/view-types/spatial-three/src/SpatialThree.js, packages/view-types/spatial-three/src/SpatialThreeSubscriber.js, packages/view-types/spatial-three/src/xr/HandDecorate.js
=> Keller mark/for each

.changeset/quiet-forks-stare.md, packages/view-types/obs-sets-manager/src/ObsSetsManagerSubscriber.js
- Treat `obsSets` as optional instead of `required` to let users work with an empty set
=> NickAkhmetov/Relax `obsSets` requirement

.changeset/neat-dingos-sip.md, packages/view-types/statistical-plots/src/FeatureBarPlot.js
=> Fix bar plot color issue

.changeset/sweet-socks-wash.md, packages/view-types/spatial-three/src/SpatialWrapper.js
=> Fix xr button styling

.changeset/xr-btn.md, packages/view-types/spatial-three/src/SpatialWrapper.js
=> Fix status check for XR button

.changeset/rich-turkeys-flow.md, packages/vit-s/src/TitleInfo.js, packages/vit-s/src/VitS.js, packages/vit-s/src/VitessceGrid.js, packages/vit-s/src/vitessce-grid-layout/VitessceGridLayout.js, sites/demo/src/vitessce-demo.jsx, sites/docs/docs/js-react-vitessce.md
=> pageMode prop

.changeset/silver-ads-report.md, packages/constants-internal/src/constants.ts, packages/main/all/src/Vitessce.tsx, packages/main/all/src/index.ts, packages/plugins/src/index.ts, packages/vit-s/src/VitS.js, packages/vit-s/src/contexts.js, packages/vit-s/src/index.js
=> Add plugin type and pass via context

.changeset/nervous-bears-arrive.md, .github/workflows/bundle-size.yml, .github/workflows/release.yml, .github/workflows/test.yml, README.md, package.json, pnpm-lock.yaml
=> Switch to official typescript v5.5

.changeset/mean-flies-compete.md, examples/configs/src/index.js, examples/configs/src/view-configs/paper-figures/cite-seq.js, examples/configs/src/view-configs/paper-figures/codex.js, examples/configs/src/view-configs/paper-figures/ims.js, examples/configs/src/view-configs/paper-figures/multimodal-ims.js, examples/configs/src/view-configs/paper-figures/multiome.js, examples/configs/src/view-configs/paper-figures/osmfish.js, examples/configs/src/view-configs/paper-figures/visium.js, packages/utils/sets-utils/src/expr-utils.js, packages/utils/sets-utils/src/expr-utils.test.js, packages/view-types/statistical-plots/src/dot-plot-hook.js, packages/view-types/statistical-plots/src/expr-hooks.js, packages/view-types/statistical-plots/src/expr-hooks.test.js
=> Figure configs, fix dot/violin plot bugs

.changeset/thirty-kids-brake.md, .github/workflows/release.yml, scripts/build-sites.sh
=> Fix versioned URLs in release notes

.changeset/tall-chicken-design.md, packages/view-types/genomic-profiles/package.json, packages/view-types/genomic-profiles/src/HiGlassLazy.js, pnpm-lock.yaml
=> Update higlass version

.changeset/mean-hats-hunt.md, sites/html/cypress/e2e/html.spec.cy.js
=> Try to fix ccf test

packages/view-types/spatial-beta/src/SpatialSubscriber.js, packages/view-types/spatial-beta/src/SpatialTooltipSubscriber.js
=> Minor updates for add obssets to tooltip

.changeset/funny-mails-tap.md, sites/docs/docs/showcase.md
=> Update showcase page

packages/types/src/ngff-types.ts
=> Shape transforms types

.changeset/heavy-maps-live.md
=> Fill in changeset

.changeset/wise-roses-suffer.md, packages/file-types/zarr/package.json, packages/file-types/zarr/src/SpatialDataShapesSource.js, pnpm-lock.yaml
=> Try webpack ignore comment

.changeset/olive-buckets-wave.md, packages/view-types/scatterplot/src/Scatterplot.js
=> Fix point layer z-index bug

examples/configs/src/view-configs/spatial-beta/blin.js, packages/legend/src/ChannelNamesLegend.js, packages/utils/image-utils/src/ImageWrapper.ts, packages/view-types/layer-controller-beta/src/ImageLayerController.js, packages/view-types/spatial-beta/src/Spatial.js, packages/view-types/spatial-three/src/three-utils.js
=> Spatial target C updates

README.md, contributing.md
This PR adds the how to contribute guidelines to the repo.
=> Added how to contribute

.changeset/witty-colts-rest.md, packages/file-types/spatial-zarr/src/SpatialDataShapesSource.js, packages/file-types/zarr/src/AnnDataSource.js
=> Spatialdata bug fix

.changeset/odd-bikes-teach.md, .github/workflows/release.yml, pnpm-lock.yaml, sites/docs/docusaurus.config.js, sites/docs/src/css/custom.css, sites/docs/src/pages/_Index.js
Fixes #1935 
Adds search to docs using docSearch provided by [Algolia](https://docsearch.algolia.com/docs/docsearch-v3)
-
=> Added search to docs using docSearch

.changeset/giant-mugs-raise.md, packages/vit-s/src/hooks.js
=> Fix useExpandedFeatureLabelsMap bug

.changeset/tender-rings-wait.md, examples/configs/src/view-configs/kpmp_spatial_atlas_oct_2024.js
=> kpmp spatial atlas - add more views

.changeset/brave-needles-lie.md, sites/docs/docs/js-react-vitessce.md
=> Update react props docs

.changeset/blue-apes-explode.md, examples/configs/src/view-configs/kpmp-premiere.js, packages/constants-internal/src/constants.ts, packages/constants-internal/src/coordination.ts, packages/main/all/src/base-plugins.ts, packages/utils/sets-utils/src/expr-utils.js, packages/vega/src/VegaPlot.js, packages/view-types/biomarker-select/package.json, packages/view-types/biomarker-select/src/ComparativeHeadingSubscriber.js, packages/view-types/biomarker-select/src/SampleSetPairManagerSubscriber.js, packages/view-types/biomarker-select/src/index.js, packages/view-types/scatterplot-embedding/src/DualEmbeddingScatterplotSubscriber.js, packages/view-types/scatterplot/src/shared-spatial-scatterplot/dynamic-opacity.js, packages/view-types/statistical-plots/src/CellSetCompositionBarPlot.js, packages/view-types/statistical-plots/src/CellSetCompositionBarPlotSubscriber.js, packages/view-types/statistical-plots/src/CellSetExpressionPlot.js, packages/view-types/statistical-plots/src/CellSetExpressionPlotSubscriber.js, packages/view-types/statistical-plots/src/DotPlot.js, packages/view-types/statistical-plots/src/DotPlotSubscriber.js, packages/view-types/statistical-plots/src/Treemap.js, packages/view-types/statistical-plots/src/TreemapSubscriber.js, pnpm-lock.yaml
Fixes #2064
Fixes #2057
Fixes #2055
-
=> Support lack of sample set selection

.changeset/shiny-foxes-smile.md, packages/file-types/zarr/src/anndata-loaders/FeatureSetStatsAnndataLoader.js, packages/file-types/zarr/src/anndata-loaders/FeatureStatsAnndataLoader.js, packages/file-types/zarr/src/anndata-loaders/ObsSetStatsAnndataLoader.js, packages/utils/sets-utils/src/expr-utils.js, packages/utils/sets-utils/src/expr-utils.test.js, packages/view-types/scatterplot-embedding/src/EmbeddingScatterplotSubscriber.js, packages/view-types/scatterplot/src/Scatterplot.js, packages/view-types/statistical-plots/src/TreemapSubscriber.js
=> Scale treemap and other fixes

.changeset/stale-planets-drop.md, examples/configs/src/view-configs/kpmp-premiere.js, packages/file-types/zarr/src/anndata-loaders/FeatureSetStatsAnndataLoader.js, packages/file-types/zarr/src/anndata-loaders/ObsSetStatsAnndataLoader.js, packages/schemas/src/file-def-options.ts, packages/view-types/statistical-plots/src/CellSetCompositionBarPlot.js, packages/view-types/statistical-plots/src/FeatureSetEnrichmentBarPlot.js, sites/docs/docs/data-file-types.mdx
Corresponds to https://github.com/keller-mark/compasce/pull/32
-
=> Improved gene set enrichment and cell type composition data loading

.changeset/clean-hotels-peel.md, examples/configs/src/view-configs/hubmap-heart.js, examples/configs/src/view-configs/kpmp-premiere.js, packages/file-types/zarr/src/anndata-loaders/ObsFeatureMatrixAnndataLoader.js, packages/view-types/statistical-plots/src/CellSetCompositionBarPlot.js
=> Minor improvements to comparative examples

.changeset/loud-toes-cough.md, packages/gl/src/SelectionLayer.js
Fixes #
https://github.com/vitessce/vitessce/issues/2094
Traverse linked list when available (in case of overlapping points, they are added as a linked list to the leaf node)
=> StefanBabukov/fix-2094 select overlapping points in SelectionLayer

.changeset/fast-bats-appear.md, sites/docs/docs/tutorial-gh-pages.mdx
This PR updates the tutorial to deploy to gh-pages. 
Todo: Need permission to update the [vitessce-demo-gh-pages](https://github.com/keller-mark/vitessce-demo-gh-pages/')
Fixes #
-
=> Updated the tutorial

.changeset/rich-lions-battle.md, examples/configs/src/view-configs/rgb-ome-tiff.js, packages/constants-internal/src/coordination.ts, packages/view-types/layer-controller/src/LayerController.js, packages/view-types/layer-controller/src/LayerControllerSubscriber.js, packages/view-types/spatial/src/Spatial.js, packages/view-types/spatial/src/SpatialSubscriber.js
=> Use PhotometricInterpretation metadata in spatial/layerController views to determine RGB vs. multiplex

.changeset/flat-poems-explode.md, sites/docs/docs/tutorial-gh-pages.mdx, sites/docs/docs/tutorial-plugin-coordination-type.mdx, sites/docs/docs/tutorial-plugin-file-type.mdx, sites/docs/docs/tutorial-plugin-view-type.mdx, sites/docs/docs/tutorial-visium.mdx, sites/docs/docusaurus.config.js
=> Tutorial updates

.changeset/hot-clocks-destroy.md, packages/neuroglancer-workers/package.json, packages/view-types/neuroglancer/package.json, packages/view-types/neuroglancer/src/Neuroglancer.js, packages/view-types/neuroglancer/src/ReactNeuroglancer.js, patches/@janelia-flyem__neuroglancer@2.37.5.patch, pnpm-lock.yaml
=> Fix neuroglancer issues in docs site / jupyter

.changeset/gorgeous-years-walk.md, examples/configs/src/view-configs/blin.js
=> Fix blin-2019 example

.changeset/soft-paws-count.md, examples/configs/src/index.js, examples/configs/src/view-configs/gene-id-mapping-example.js, examples/configs/src/view-configs/testConfig.js, packages/view-types/biomarker-select/src/default-async-functions.js
This PR changes the url/aws-bucket used for the genes list. 
The testConfig is added for testing purposes, and will be removed before merge. 
Fixes #
-
=> Changed url for genes file'

.changeset/short-gifts-jog.md, examples/configs/src/view-configs/habib_2017_nature_methods.js, packages/main/all/src/joint-file-types.ts, packages/schemas/src/file-def-options.ts
Towards https://github.com/vitessce/vitessce-python/issues/446
-
=> Add obsFeatureColumns option

.changeset/early-donuts-smoke.md, examples/configs/src/index.js, examples/configs/src/view-configs/spatial-beta/spatialdata-kpmp.js, packages/file-types/spatial-zarr/src/SpatialDataShapesSource.js, packages/file-types/spatial-zarr/src/spatialdata-loaders/SpatialDataObsSegmentationsLoader.js, packages/file-types/spatial-zarr/src/spatialdata-loaders/SpatialDataObsSpotsLoader.js, packages/file-types/spatial-zarr/src/spatialdata-loaders/index.js, packages/main/all/src/base-plugins.ts, packages/main/all/src/joint-file-types.ts, packages/schemas/src/file-def-options.ts, packages/utils/spatial-utils/src/index.js, packages/utils/spatial-utils/src/spatial.js, packages/view-types/spatial-beta/src/Spatial.js
Fixes https://github.com/vitessce/vitessce/issues/1835
-
=> Support spatialdata polygons (shapes)

.changeset/cold-hats-play.md, packages/view-types/statistical-plots/src/CellSetExpressionPlotSubscriber.js
=> Violin plot title should use featureValueType

.changeset/nice-falcons-unite.md, packages/file-types/spatial-zarr/src/SpatialDataShapesSource.js, packages/file-types/spatial-zarr/src/spatialdata-loaders/SpatialDataObsSpotsLoader.js
=> Fix bug preventing axis normalization for obsSpots with transformations

.changeset/chilled-impalas-repeat.md, packages/main/all/src/base-plugins.ts
=> Fix registration of zip-based fileTypes for SpatialData

.changeset/cool-rabbits-teach.md, packages/legend/src/Legend.js, packages/view-types/spatial-beta/src/Spatial.js
=> Fix coloring by expression values for segmentation polygons in spatialBeta view

.changeset/four-brooms-search.md, packages/gl/src/bitmask-utils.js, packages/view-types/spatial-beta/src/Spatial.js
=> Update how missing values are passed to BitmaskLayerBeta

.changeset/soft-rockets-divide.md, examples/configs/src/view-configs/3d-maps/blood-vessel-named.js, examples/configs/src/view-configs/3d-maps/blood-vessel-neighborhood.js, examples/configs/src/view-configs/3d-maps/jain-kidney-decimated.js, examples/configs/src/view-configs/3d-maps/link-controller-minimal.js, packages/view-types/link-controller/src/LinkController.js
Fixes #
The workflow for using the Link Controller updated over time and we transition from using a description field to an own view
- Adding the Vitessce Link Controller instead of a description field for 3 examples
=> Adding link controller to examples

.changeset/honest-glasses-grab.md, examples/configs/src/view-configs/3d-maps/jain-kidney-decimated.js, packages/view-types/link-controller/src/LinkController.js
Fix that the Link controller doesn't request a new ID when getting it from the Config
Fixes #
- Link Controller adding a "else" that the ID is not overwritten when getting it from the config
- Using custom spacing for the example with Sanjays data in sanjay-2024
=> fix the link controller overwriting the link id from config

.changeset/gorgeous-forks-love.md, packages/file-types/spatial-zarr/src/SpatialDataShapesSource.js
=> Assume WKB geometry encoding when lack of encoding metadata 
