vitessce/vitessce

- src/components/AbstractSelectableComponent.js
- src/components/ToolMenu.js
- src/components/tools.js
Converts the `isSelecting` boolean to enum (using string constants) to be able to specify additional tools such as `SELECT_POLYGON` or `SELECT_LASSO` in the future.
- Would it make more sense for the `tools.js` file be located at `src/tools.js` instead of `src/components/tools.js`?
> Specify active tool in ToolMenu via enum rather than boolean

- package-lock.json
- package.json
- src/components/AbstractSelectableComponent.js
This pull request updates deck.gl to v7 (on which the current version of nebula.gl depends).
The change to AbstractSelectableComponent is based on this comment https://github.com/uber/deck.gl/issues/3259
> Update deck.gl to ^7.1.4

- CHANGELOG.md
- src/components/factors/Factors.js
- src/components/genes/Genes.js
- src/css/index.css
- src/css/radio.module.css
Before committing myself to this, I wanted to run it by you, @keller-mark. I've pulled out the radio button styling into a css module.
- Maintenance is easier, because dependencies are explicit in the code, rather than depending on global styles
- CSS interaction bugs are reduced, because elements get only the rules they need.
- Related: Reuse is improved... Web components with shadow DOM won't inherit bad styles... and I guess we could inject a style tag, but that seems worse.
This isn't necessary... but I do think it will save time in the future... but it will take some time to untangle things now...
Towards #227.
> Demonstration of CSS modules

- src/layers/utils.js
It seems that the new version of deck.gl does not actually render the cells with new colors unless the array reference changes.
Fixes #299
> Fix gray cells

- cypress/integration/vitessce.spec.js
- src/app/api.js
- src/app/componentRegistry.js
Fix #305. Rather than a prefix or suffix, I'm just using lowercase: That should be enough to indicate that we're in a different namespace?
> Use simple names in registry

- src/css/app.scss
Fix #367 (Sorry, meant Safari, not Chrome in commit message.)
> Prevent pane titles from shrinking on Safari

- CHANGELOG.md
- src/css/_app.scss
Fixes #366. Adds CSS styles that are enabled during resize because react-grid-layout/react-resizable/react-draggable adds the `react-draggable-transparent-selection` class to the `body` element while resizing.
> CSS fix for safari text-selection-during-resize bug

- CHANGELOG.md
- src/layers/SelectionLayer.js
Fixes #442 
This fixes the issue, but reverts back to drawing the rectangle by clicking, rather than dragging. Is that a deal-breaker?
Also, I looked into dropping the "forked" SelectionLayer, and just using the one published by nebula.gl, but they still have a hack-y way of doing polygon selection with a setTimeout ([here](https://github.com/uber/nebula.gl/blob/3a4e974dedf7937013cd65f5a6c71a6df78ee4d1/modules/layers/src/layers/selection-layer.js#L116)), which we do not do in our implementation
> Fix rectangle selection issue

- .gitignore
- CHANGELOG.md
- demo/src/index.html
- src/app/Welcome.js
- src/components/sets/PopoverColor.js
- src/components/sets/PopoverMenu.js
- src/css/_app.scss
- src/css/_bootstrap-minimal.scss
- src/css/_controls.scss
- src/css/_popover.scss
- src/css/_sets-manager.scss
- src/css/index.scss
- Fixes #412 
- Fixes #396 
- Fixes #395 
This pull request removes the bootstrap <link/> tag from the demo index.html, instead putting the bootstrap styles we are using into a mixin in the file `_bootstrap-minimal.scss`. This mixin is used by the `.vitessce-container` class.
I also added styles for `body` and `.container-fluid` to `_app.scss` outside the `app` mixin, since these elements are parents of `.vitessce-container`.
> Remove bootstrap, convert things to scss mixins

- CHANGELOG.md
- src/app/Welcome.js
The dark background comes from this css target: `.vitessce-container .react-grid-layout`, so I'm adding an extra div so that rule applies, and manually setting the height to 100vh.
> Add dark background to homepage. Fix #468

- CHANGELOG.md
- src/app/Welcome.js
Overkill, but we keep on losing the space before the `<b>`: This should fix that. Does remove the dash in "single-cell", but I think it's worth it.
> Fix spacing on homepage

- CHANGELOG.md
- src/app/app.js
This may be helpful with hubmap debugging: The portal will generate a viewconf which has a bug, but I can look in the logs, get the data-uri and run it on localhost or vitessce.io, figure out what changes are needed in the configuration, and then edit the portal-ui source-code with exactly the changes I need.
(Emoji in log is gratuitous, but it makes it easier to spot.)
> Log viewconf as data-uri

- CHANGELOG.md
I like to start the new section as soon as the old one is tagged; Without a blank section at the top, it's easy for the next person to keep updating the old section by mistake. (There are npm utils that will help with changelogs, but that seemed like more trouble than it's worth... that could be the wrong call.)
> Add new section to changelog

- CHANGELOG.md
- GLOSSARY.md
- src/app/PubSubVitessceGrid.js
- src/components/layerpublisher/index.js
- src/components/sourcepublisher/SourcePublisher.js
- src/components/sourcepublisher/index.js
This switches the names at a high level... but there are still all the methods and attributes that reference "layers"... If they are inside spatial it may be ok, but everywhere else it needs to change... One option would be to change layer to source everywhere, and only after this is done, switch back the ones in Spatial... Or might be better to continue these incremental changes, one method and one field at a time.
Thoughts?
> Rename LayerPublisher to SourcePublisher

- CHANGELOG.md
- package.json
This is just a PR so that the versioning on github reflects the versioning on NPM (from the push made yesterday)
The readme currently says:
> We publish to the NPM registry by hand: Update the version number in package.json and run npm publish.
> 
> Finally, update the CHANGELOG.md to point to the new release on NPM.
Is there any reason not to automate this? I understand the need for a more manual demo push process but it seems that the NPM push process should be done by [travis](https://docs.travis-ci.com/user/deployment/npm/). I can think of two ways to exert a bit more control over this that we may want to consider:
- Use git tags to tag commits on `master` as new versions. Only if travis detects one of these tags would we push to NPM
- Use a `dev` branch and a `master` branch. Merge …
> Version bump to reflect latest NPM version

- CHANGELOG.md
- src/css/_app.scss
In manual testing of the latest demo, I realized that the "33 genes" subtitle of the Expression Levels box now overflows and produces an ugly horizontal scrollbar (at least on smaller screens). I had fixed this in the metadata tables commit [here](https://github.com/hubmapconsortium/vitessce/pull/529/files#diff-d03831d6209c2a1d75ade544679e736bR50) but now that we are waiting to merge that, I had to make a separate one-line fix in a this PR.
> Fix horizontal scroll bug

- CHANGELOG.md
- demo/index.html
Fixes #537. I believe this bug was caused by minification of HTML which must have changed with the new bundling scripts.
This also updates the font of the info text which changed after removing the bootstrap dependency.
> Fix spacing bug

- CHANGELOG.md
- src/app/app.js
- src/app/index.js
- src/demo/index.js
- src/index.js
Fixes #542 
Removes all reference to ReactDOM from `app.js` and moves the rendering step into the `src/demo/index.js` file.
It seemed like the only reason the render step was in the code was to be able to wait for a promise, which I had to abstract into a new `AwaitResponse` component.
> Separate rendering from validation

- CHANGELOG.md
- src/components/layer-controller/LayerController.js
- src/index.js
Fixes two small things I noticed.  The components all exported as one object, as opposed to being separate ones i.e `import vitessce from 'vitessce'` and then `const { Vitessce } = vitessce;` as opposed to `import { Vitessce } from 'vitessce'`.  The other thing is because the `metadata` is optional and not necessarily used for all tiffs.
> Small tweaks

- CHANGELOG.md
- scripts/webpack.config-lib.js
The current bundle contains react and react-dom but should not (see #542)
It seems that I had this externals object backwards.
Bundle size goes from 2.99 MB to 2.77 MB
> Reverse externals object in webpack config

- CHANGELOG.md
- src/components/layer-controller/LayerControllerSubscriber.js
- src/css/_higlass.scss
Fixes #556 (hopefully). With the `disableGlobal: true` [line](https://github.com/hubmapconsortium/vitessce/compare/keller-mark/fix-556?expand=1#diff-b5e59db8e37a6f3bf2153d6161dc58d2R18), all the MUI classes include random suffixes, which you can see  in the firefox style inspector.
This PR also comments out the higlass styles, since they also bleed a bit and not sure how to resolve that right now. We can just make an issue for it, I don't think it is a big deal since we do not have any public demos that use the vitessce higlass component yet.
> Add mui class generator disableGlobal option

- .gitignore
- CHANGELOG.md
- package.json
- push-demo.sh
- scripts/paths.js
The Glasgow team asked that the `src/` directory be pushed to NPM so they can use the components from the source files rather than using the bundled versions and needing to double-bundle.
> Publish src/ to NPM

- CHANGELOG.md
- src/components/cell-tooltip/CellTooltip.js
- src/components/cell-tooltip/CellTooltip1DVertical.js
- src/components/cell-tooltip/CellTooltip1DVertical.test.js
- src/components/cell-tooltip/CellTooltip1DVerticalSubscriber.js
- src/components/cell-tooltip/CellTooltip2D.js
- src/components/cell-tooltip/CellTooltip2D.test.js
- src/components/cell-tooltip/CellTooltip2DSubscriber.js
- src/components/cell-tooltip/CellTooltipContent.js
- src/components/cell-tooltip/index.js
The Glasgow team wants to be able to use any React component as tooltip contents.
I added an extra `CellTooltipContent` component to abstract this, and added some getter functions as props that can be overridden.
> Add CellTooltipContent abstraction

- package-lock.json
- package.json
- src/app/api.js
- src/components/layer-controller/ChannelController.js
- src/components/layer-controller/ChannelOptions.js
- src/components/layer-controller/LayerController.js
- src/components/layer-controller/LayerControllerSubscriber.js
- src/components/layer-controller/LayerOptions.js
- src/components/layer-controller/constants.js
- src/components/layer-controller/reducer.js
- src/schemas/fixtures/raster.good.json
- src/schemas/raster.schema.json
This PR contains: 
1. Basing slider values on max/min of the raw data or the full range, as well as updating to the IQR 
2. Initial selections for viewing images.
3. Docs for the layer controller and its sub-components.
4. Updates camel casing for the `raster` schema - I'll make a separate PR for the `cell_sets_tabular` schema that also has non-camel cased keys.
5. A `renderLayers` key for initial rendering in the `raster` schema.  The order provided here is the order in which the images render.
The default right now is Max/Min for the sliders.  
The current default selections for a given `image` will be the midpoint of the global dimensions (z and time) as well as the first four channels of the first selectable dimension found (such as "channel" or "mz").
> Initial Slider Values and Selections

- src/components/scatterplot/Scatterplot.js
- src/components/spatial/Spatial.js
This is a PR into Trevor's PR.
In playing around with the code, it looks like the `onViewStateChange` is not necessary (I now wonder if it ever was?), and at least not a correct prop for the `ToolMenu` component (not sure how it got there, it may have been from me when refactoring the AbstractSelectableComponent).
> Remove onViewStateChange

- .travis.yml
- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/app/Welcome.js
- src/app/app.js
- src/components/TitleInfo.js
- src/components/classNames.js
- src/components/scatterplot/Scatterplot.js
- src/components/scatterplot/ScatterplotSubscriber.js
- src/components/spatial/Spatial.js
- src/components/spatial/SpatialSubscriber.js
- src/css/_app.scss
- src/layers/utils.js
This pull request:
- sets the `cellRadiusScale` prop of the `<Scatterplot/>` component based on a heuristic relative to the `extent` of the cell mapping x-y coordinates (the rectangular area). While the previous setting was fine for Linnarrsson and Dries, I was noticing the fixed radius scale was too large for the scatterplots in the portal. In the process I converted the ScatterplotSubscriber to a function component.
- fixes the `<Spatial/>` background color to black regardless of the theme. I know we discussed some potential imaging modalities that may look better on white. It sounded like the heuristic for that will be figured out later, correct?
- In a recent pull request, I updated the non-selected cell encoding to use opacity. However, I noticed that it looked bad when there was …
> Dynamic scatterplot radius scale, spatial black background, and selection color mixing

- .travis.yml
- CHANGELOG.md
- package-lock.json
- package.json
- src/app/PubSubVitessceGrid.js
- src/components/layer-controller/ChannelOptions.js
- src/components/layer-controller/ImageAddButton.js
- src/components/layer-controller/styles.js
- src/css/_bootstrap-minimal.scss
This pull request upgrades to the latest version of vitessce-grid, in which the VitessceGrid component takes the `height` prop.
Also, this adds the `disablePortal` prop to the `Popper` tooltip component from material-ui, so that the tooltip elements not rendered outside of the `Vitessce` component, which allows them to respect the `z-index` css. Z-index needs to be added in the portal expanded mode, otherwise the file listing table heading appears at a higher z-index than Vitessce.
There should be no visible change
> Pass height prop to VitessceGrid

- CHANGELOG.md
- src/components/layer-controller/ChannelController.js
- src/components/layer-controller/ChannelController.test.js
- src/components/layer-controller/ColorPalette.js
- src/components/layer-controller/LayerController.js
- src/components/layer-controller/LayerControllerSubscriber.js
- src/components/layer-controller/styles.js
We keep the underlying representation as white and then render grey only when the channel controller sees that white and the theme is light.  In addition, this adds a little border around the color palette icons to distinguish the white from the white background.  Please feel free to check out and let me know if everything looks good!
> Channel Controller Light Theme Tweaks

- CHANGELOG.md
- src/components/scatterplot/Scatterplot.js
- src/components/spatial/Spatial.js
This adds the prop `cellOpacity` for Scatterplot and Spatial, which allows passing a value for the `opacity` deck.gl prop. By default, `1.0`
> Add a cellOpacity prop

- CHANGELOG.md
- src/components/layer-controller/ColorPalette.js
Hopefully this fixes #600 .  I suppose it makes sense we get odd behavior when the button is smaller than the icon it wraps.
> Remove height css from color paletter

- CHANGELOG.md
- src/components/heatmap/HeatmapCellColorCanvas.js
- src/components/heatmap/HeatmapCellSelectionCanvas.js
- src/components/heatmap/HeatmapDataCanvas.js
- src/css/_heatmap.scss
- src/css/index.scss
Fixes #368.  
Basically, as I understand it, the `absolute` positioning gives us the control we need to force the `canvas` elements to "fill" the container, but this means we need to tell the css how to position them, hence the multiple `top` styles.  
Also, this `absolute` position means the canvases are unaware of the padding, except to know where they should start (from the padded top and left), and thus they need to be told to inherit the padding of the parent. 
Finally, the `left: 0` forces the canvases to start from the parent container's left-most bound (before padding) and then applying the same padding again while the `width: 100%` tells the canvases to fill out the parent container.  Without this `left: 0` style, the padding would be applied twice and the canvas would be too far …
> Fix Heatmap Safari

- src/components/heatmap/Heatmap.js
- src/components/heatmap/HeatmapCellSelectionCanvas.js
- src/components/heatmap/HeatmapDataCanvas.js
- src/css/_heatmap.scss
This is a PR into your PR #609. It looked like in that PR the height of the top two heatmap components changed to different heights, so I made these changes to keep them the same.
Here I added a new `<div>` around the 3 heatmap elements that handles the padding issue so that the inner heatmap elements do not need to worry about it.
> Keep top two parts of heatmap the same height

- CHANGELOG.md
- src/components/heatmap/Heatmap.js
- src/components/heatmap/HeatmapCellSelectionCanvas.js
- src/components/heatmap/HeatmapDataCanvas.js
- src/css/_heatmap.scss
This gives the top of the selection canvas (grey) padding so that as you resize, the color canvas (all the little lines) stays visible.
> Give the top of the selection canvas padding

- CHANGELOG.md
- src/schemas/cell-sets.schema.json
This is an update to the cell sets schema to allow hierarchy levels to contain both leaf and non-leaf nodes. This removes the need for the extra level of "any" leaf nodes.
A demo of this use case is here (demo of the `keller-mark/probabilistic-cell-sets-demo` branch) https://s3.amazonaws.com/vitessce-data/demos/2020-07-01/e59a786/index.html?dataset=7fd04d1aba61c35843dd2eb6a19d2545&theme=dark
and we can verify that the existing Linnarsson and Dries datasets validate under this expanded schema here https://s3.amazonaws.com/vitessce-data/demos/2020-07-01/e59a786/index.html?dataset=dries-2019&theme=dark and https://s3.amazonaws.com/vitessce-data/demos/2020-07-01/e59a786/index.html?dataset=linnarsson-2018&theme=dark
> Update cell sets schema

- CHANGELOG.md
- src/components/layer-controller/LayerController.js
This is sadly the best I came up with.  It seems that part of the problem is that there is not much distinction between the icon and the name.    I found https://stackoverflow.com/questions/53221621/how-to-wrap-or-truncate-long-strings-in-a-material-ui-expansionpanelsummary but it requires an absolute width of some sort, so I suppose we could provide a callback to get hat width.  Open to other suggestions if anyone has run into this before.  I tried using an absolutely positioned div to wrap the text but that ended up messing with the lower down parts of the component.  Any suggestions welcome.  Here is what it looks like:
> Overflow Controller Text

- CHANGELOG.md
- src/components/vega/VegaPlot.js
This PR should fix https://github.com/hubmapconsortium/portal-ui/issues/571 by no longer using React.lazy.
Not the ideal fix, but should be fine for now until we have a chance to think about other options that will allow us to use React.lazy here in vitessce, and then consume those components in the portal.
> Remove React.lazy wrapper around react-vega

- CHANGELOG.md
- src/app/PubSubVitessceGrid.js
This pull request fixes an issue where, even though the Vitessce `height` changes, the `useGridItemSize` hook does not know to respond because it does not receive any event for this change. This adds a new place where `GRID_RESIZE` is published in `PubSubVitessceGrid` when the `rowHeight` variable changes (using `useEffect` to listen for this change).
This allows the VegaPlot to be resized when the Vitessce component is made full-window in the portal. Previously, the `useGridItemSize` hook did not respond to this change, and the VegaPlot incorrectly kept its previous dimensions
> Fix grid item size hook by publishing an additional GRID_RESIZE

- CHANGELOG.md
- src/components/genes/GenesSubscriber.js
This updates the UI for #481 so that the portal can override this to show `antigens` instead of `genes`.
> Add labelOverride prop for genes component

- CHANGELOG.md
- src/app/PubSubVitessceGrid.js
- src/app/app.js
- src/components/sourcepublisher/SourcePublisher.js
This adds a prop `onWarn` for an optional callback function. This will be called with any messages emitted to the `STATUS_WARN` event, so that a consumer app (the portal) can manage the display of warning messages (e.g. in a "toast" component that does not take up vitessce grid real estate). I removed the "Details in console" part of the errors since those seem useful to developers only.
Fixes #249
> Add onWarn callback to Vitessce component

- CHANGELOG.md
- src/components/spatial/Spatial.js
Can you pull this and play around with it?   I set a cutoff for the stroked boundary so that the selection is nicer.
I think .7 is a good cutoff but I could be wrong: 
```javascript
getLineWidth: cellOpacity < 0.7 ? 10 : 0
```  
Without the cutoff the boundary and the interior are both selectable, even when opacity is 1, which is an odd interaction.  If there is a better way to do this, please let me know!
> Make cell boundaries default with opacity < ?

- CHANGELOG.md
- src/components/layer-controller/LayerOptions.js
- src/components/layer-controller/RasterLayerController.js
- src/components/layer-controller/reducer.js
This PR provides reasonable defaults for RGB and importantly turns off the layer controller for those assays.
You can replace the Spraggins layer schema with this on line 56 of `api.js`: 
```javascript
const vanderbiltBase = {
description: vanderbiltDescription,
layers: [{
name: 'raster',
type: 'RASTER',
url: URL.createObjectURL(new Blob([JSON.stringify({
schemaVersion: '0.0.2',
images: [{
name: 'Spraggins PAS',
url:
'https://vitessce-demo-data.storage.googleapis.com/test-data/hubmap/pyramid_0.0.2/VAN0011-RK-3-10-PAS_registered.ome.tif',
type: 'ome-tiff',
metadata: {},
}],
})])),
}],
};
```
> RGB defaults

- CHANGELOG.md
- src/components/heatmap/HeatmapSubscriber.js
The cypress tests sometimes fail and sometimes succeed (https://github.com/hubmapconsortium/vitessce/pull/665) so hopefully this fixes it.  The first failure was https://travis-ci.org/github/hubmapconsortium/vitessce/builds/710375361.  
The error is: 
```
Uncaught TypeError: selectedCellIds.has is not a function
```
I was able to get the fail/succeed intermittently locally but this appears to have stabilized things by defaulting the `selectedCellIds` to a `Set` like it was before: https://github.com/hubmapconsortium/vitessce/pull/653/files#diff-3a2e6f776ecea6c621c38d0489c802f5L15 so I assume this happened in #653 but we didn't see it until later.
> Fix cypress tests.

- CHANGELOG.md
- src/components/layer-controller/RasterLayerController.js
I noticed this small bug while doing release testing so this fixes #668.  The slider range was being changed on one side when the domain changed.
> Slider fix

- CHANGELOG.md
- README.md
- src/components/spatial/Spatial.js
When I was testing out the latest Vitessce in the portal, I noticed the cell boundary should be determined by pixel size, not the view space size alone.  The issue is that the width before this change was controlled entirely by the size in the "coordinates" of the view space so smaller images with the same width would show a much larger boundary.  Now, we can manage the pixel size directly.
Without this fix, this is what things look like in the portal:
With the fix, this what things look like:
> Cell Boundary Determined by Pixel Size

- CHANGELOG.md
- src/components/layer-controller/LayerOptions.js
I set up the Viv loaders to always have a Z and T dimension for OME-TIFF, even if there is only one value present (i.e 0).  [Chuck recently also pointed](https://github.com/hubmapconsortium/portal-ui/pull/880#issuecomment-663559131) out that displaying the sliders is not particularly informative so I am removing them here.
To test and see that a slider does not appear when there is no z or t dimension, you can replace the Spraggins layer schema with this on line 56 of `api.js`: 
```javascript
const vanderbiltBase = {
description: vanderbiltDescription,
layers: [{
name: 'raster',
type: 'RASTER',
url: URL.createObjectURL(new Blob([JSON.stringify({
schemaVersion: '0.0.2',
images: [{
name: 'Spraggins PAS',
url:
'https://vitessce-demo-data.storage.googleapis.com/test-data/hubmap/pyramid_0.0.2/V …
```
> Remove global dimensions if there is only one.

- CHANGELOG.md
- src/app/PubSubVitessceGrid.js
Fixes #682.
This branch:
Previously:
> Fix spacing on TitleInfo

- CHANGELOG.md
- src/components/genes/GenesSubscriber.js
- src/components/heatmap/HeatmapSubscriber.js
- src/components/spatial/Spatial.js
- src/components/spatial/SpatialSubscriber.js
Noticed that there is also a "genes" label in the heatmap, so this allows for an override of that.  Related to #481 and completing the work from #630.
Tested in the portal and it works:
> Label overrides.

- CHANGELOG.md
- src/components/sets/TreeNode.js
Fixes #697.
You can test by
1. going to the Dries example http://localhost:3000/?dataset=dries-2019&theme=dark
2. click the arrow next to "Leiden Clustering" to expand to show the individual clusters
3. click the blue color next to "Cluster 1"
4. click "Cluster 1" text
crashes on http://vitessce.io/?dataset=dries-2019&theme=dark, should be fixed here.
> Fix bug by preventing leaf nodes from calling onNodeExpand function

- CHANGELOG.md
- package-lock.json
- package.json
This will make some PAS imaging a little nicer in the portal.  There shouldn't be any noticeable changes in the vitesce demos.
> Upgrade Viv to 0.3.2

- CHANGELOG.md
- package-lock.json
- package.json
I used `npm version minor` due to the new `fileType` requirement in view configs, since this is a "breaking change" for old view configs.
> Version bump v0.2.0

- CHANGELOG.md
- src/components/heatmap/Heatmap.js
I had a typo in the Heatmap prop names, preventing the HeatmapSubscriber from passing down the axis title override value (for example "Genes" -> "Antigens")
I realized this when testing out the v0.2.0 in the portal for CODEX data (in draft PR here https://github.com/hubmapconsortium/portal-ui/pull/942).
This can be tested here by replacing lines 180-182 in api.js https://github.com/hubmapconsortium/vitessce/blob/master/src/app/api.js with 
```js
props: {
transpose: true,
variablesLabelOverride: 'antigen',
},
```
> Fix heatmap "Genes" axis title override bug

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/PubSubVitessceGrid.js
- src/app/vitessce-grid/VitessceGrid.js
- src/app/vitessce-grid/VitessceGrid.test.js
- src/app/vitessce-grid/index.js
- src/app/vitessce-grid/layoutUtils.js
- src/app/vitessce-grid/layoutUtils.test.js
- src/layers/HeatmapCompositeTextLayer.js
In this PR I copied the vitessce-grid files into `src/app/vitessce-grid/`, removing the `vitessce-grid` dependency and replacing with `react-grid-layout` dependency directly (first commit https://github.com/hubmapconsortium/vitessce/pull/708/commits/6bcef5f33ff3202a9dd12fd88a37648155876ef1). In the second commit I moved the `onAllReady` call in `VitessceGrid.js` into a useEffect to fix the warning noted in #707. In the third commit I updated the tests (for some reason Enzyme `shallow()` was not working correctly, so I changed to `mount()`)
> Copy vitessce grid and resolve React warning

- CHANGELOG.md
- src/components/layer-controller/ChannelController.js
- src/components/layer-controller/RasterLayerController.js
Mirroring what we did here: https://github.com/hms-dbmi/viv/pull/262/files
This PR truncates the displayed slider values when you hover over one of the ends.
> Clean up 32bit sliders.

- src/components/layer-controller/LayerOptions.js
- src/components/layer-controller/RasterLayerController.js
This should actually work.  Even though the slider worked previously, the selections were not exactly right. It should have been a red flag that that implementation looked considerably simpler than the previous one.  This looks more like the original way this was (pre-`next`).
> Fix Global Controllers (Again)

- CHANGELOG.md
- src/app/view-config-utils.js
- src/app/view-config-utils.test.js
- src/components/layer-controller/LayerControllerSubscriber.js
- src/components/spatial/SpatialSubscriber.js
This may fix the dataset update bug - I was only able to try with the Cell Type Annotation preview datasets - for some reason the Datasets search page is not working in my local `portal-ui` instance. 
I think perhaps what is happening is that, in the portal, since the view configs have version `0.1.0`, when they are "upgraded" to `v1.0.0`, they are all being assigned the same dataset ID. The data hook functions check the dataset ID to determine whether the `useEffect` needs to be re-run. If it is always "A", then perhaps it is not re-running as expected when a new dataset is selected from the portal dataset dropdown.
> Try to fix dataset update bug

- src/components/sets/CellSetsManagerSubscriber.js
- src/components/sets/TreeNode.js
- src/components/sets/cell-set-utils.js
- src/components/sets/cell-set-utils.test.fixtures.js
- src/components/sets/cell-set-utils.test.js
This pull request fixes some edge cases:
- allow dragging a node to re-order it among its current siblings (in `hasSiblingNameConflict` only "find" nodes that are not identical object references)
- Don't allow a leaf node to become a top-level ("level zero") node.
- Update the nodeTransform calls: in two cases, you want to match on the `dropParentPath` and in another case you want to match on `dropPath`
- Removes code related to `_state` and the `nodeClearState` function, and removes the `eslint-disable no-underscore-dangle`
> Minor drag-and-drop bug fixes

- CHANGELOG.md
- src/components/layer-controller/ChannelController.js
- src/components/layer-controller/LayerOptions.js
- src/components/layer-controller/RasterLayerController.js
- src/components/spatial/Spatial.js
- src/components/spatial/constants.js
- src/components/spatial/utils.js
- src/schemas/config.schema.json
This PR updates the spatial layers schema:
- adds descriptions to raster properties
- changes the "None" `colormap` value to `null` rather than the empty string (although empty string still needs to be used in some places internally)
- removes `domain` property from the raster channel definition schema, and instead we now only use the layer-level `domainType` to prevent potential discrepancies
> Remove domain from spatialLayers raster channels array items

- CHANGELOG.md
- src/components/data-hooks.js
- src/components/layer-controller/ChannelController.js
- src/components/layer-controller/ImageAddButton.js
- src/components/layer-controller/LayerControllerSubscriber.js
- src/components/layer-controller/LayerOptions.js
- src/components/layer-controller/RasterLayerController.js
- src/components/layer-controller/VectorLayerController.js
- src/components/spatial/Spatial.js
- src/components/spatial/constants.js
- src/components/spatial/utils.js
- src/schemas/config.schema.json
Besides the schema the two code changes were to fix:
1. The `moleculesLayer` has no use for `stroked` but it was being set anyway (note the diff) so now we are stricter about what layer the controller sets it for.
2. The `index` property of a layer was a string because `nextImageLoaders` and `nextImageMeta` were objects that had indices which were numbers (they seem like they were supposed to be arrays) so getting their `Object.entries` gave a string instead of a number.
> Validate Spatial Layers

- CHANGELOG.md
- src/components/sets/CellSetsManagerSubscriber.js
I am starting to do release testing and came across this.
To reproduce this, you can checkout master and go to "Dries" and then try to add a hierarchy and a warning will appear in the status box.
Thus we make sure to initialize our `addditionalCellSets` tree with a version/datatype.
> Fix additionalCellSets with no verison

- CHANGELOG.md
- src/components/layer-controller/ChannelController.js
I am starting to do release testing and came across this.
We introduced a bug [here](https://github.com/hubmapconsortium/vitessce/pull/777/files#diff-99a1fee50b021c3e95cef3ee3db4966a7e70f7343ede2c50444276b1706ca058R158-R185) where the domain of the slider visually does not update if the loader selection changes.
> Fix Loader Selection-Domain Issue

- CHANGELOG.md
- src/components/sets/CellSetsManagerSubscriber.js
- src/components/sets/cell-set-utils.js
This makes the cell set operations able to be used more liberally, which saves on computation time for large cell sets.
> Make cell set options less restrictive.

- .github/workflows/deploy.yml
- CHANGELOG.md
Forgot that this environment variable needs to be set for each step that runs `build` and the `prepublish` step includes the build
> Fix deploy bug

- .github/workflows/deploy.yml
- CHANGELOG.md
The deployment workflow failed because NPM (correctly) rejected a new package with the same version as an existing published package. We can add the `continue-on-error` tag to the NPM publish step so that this workflow succeeds regardless.
Also, I learned last night while reading the actions documentation that `env` can be specified at the _job_ level as well as the _step_ level. Here I just used that to remove the small code duplication
> Deploy workflow should succeed despite no change to package version

- CHANGELOG.md
- src/components/sets/CellSetsManagerSubscriber.js
- src/components/sets/cell-set-utils.js
- src/components/sets/io.js
- src/components/sets/io.test.js
- src/loaders/anndata-loaders/CellSetsZarrLoader.js
- src/schemas/cell-sets-tabular.schema.json
- src/schemas/config.schema.json
- src/schemas/fixtures/cell-sets-tabular.good.json
It was bugging me that the cell-sets-tabular schema uses snake_case. I wanted to fix this now while I don't think anyone is relying on this feature yet ( / before it is documented). In this PR I changed it to use camelCase, and also updated the AnnData loader.
I also fixed some CSV/JSON file import/export bugs - there were issues due to changes to the way that set colors are handled now that we use `additionalCellSets`
> Use camelCase rather than snake_case in schema

- CHANGELOG.md
- package-lock.json
- package.json
- src/layers/HeatmapBitmapLayer.js
- src/layers/PixelatedBitmapLayer.js
Because of https://github.com/visgl/deck.gl/pull/5197 we have to change the way we interact with `BitmapLayer` - the upgrade to 0.8.1 in Viv also gives interleaved-rgb support.
> Upgrade Viv to 0.8.1 and deck.gl to 8.4.0-alpha.4

- CHANGELOG.md
- src/api/VitessceConfig.js
- src/api/VitessceConfig.test.js
- src/app/VitessceGrid.js
- src/app/api.js
- src/app/vitessce-grid-utils.js
- src/components/data-hooks.js
- src/components/description/DescriptionSubscriber.js
- src/schemas/config.schema.json
Fixes #813 
This adds an optional `description` property to dataset definitions in view configs. Also, I added a `useDescription` hook which the `<Description/>` component can use to get this value based on its dataset assignment from the coordination space.
> View config dataset descriptions

- CHANGELOG.md
- src/loaders/anndata-loaders/BaseAnnDataLoader.js
I seem to have tracked down the issue with string decoding mentioned in #807.  I have noticed there is a "header" in both JSON and VLenUtf8 `numcodecs` compressors for strings.  For example, with JSON, this is the output in the file where the first four bytes (i.e the number 6) correspond to the chunk size, which is the number of string elements in this array (each one separated by `3,0,0,0`):
```
[6,0,0,0,3,0,0,0,102,111,111,3,0,0,0,98,97,114,3,0,0,0,122,97,112,4,0,0,0,106,97,122,122,3,0,0,0,102,111,111,3,0,0,0,98,97,114,"|u1",[47]]
```
from this python:
```python
import zarr
import numcodecs
compressor = numcodecs.JSON()
z = zarr.open_array('~/test_str.zarr', chunks=(6,), shape=(20,), compressor=compressor, dtype=str, fill_value='foo', mode='w')
z[:] = ['foo', 'bar', 'zap', 'jazz', …
```
> Fix AnnData Text Decoding.

- CHANGELOG.md
- src/loaders/anndata-loaders/BaseAnnDataLoader.js
- src/loaders/anndata-loaders/MatrixZarrLoader.js
There are a [few](https://github.com/vitessce/vitessce/blob/0abec9d46f5bed14f31325c308ad7adbfb0adf00/src/loaders/anndata-loaders/MatrixZarrLoader.js#L108-L116) different [spots](https://github.com/vitessce/vitessce/blob/0abec9d46f5bed14f31325c308ad7adbfb0adf00/src/loaders/anndata-loaders/BaseAnnDataLoader.js#L70-L82) where our AnnData loaders load a flattened array by fetching a key directly, but could be more robust to error if they kept trying to fetch the data until they couldn't find any.  Thus this PR refactors these lines of code to be reusable:
https://github.com/vitessce/vitessce/blob/0abec9d46f5bed14f31325c308ad7adbfb0adf00/src/loaders/anndata-loaders/BaseAnnDataLoader.js#L132-L154
The `getFlatArrDecompressed` method is now used wherever a flat array is needed directly from the …
> Fix Flat Array Parsing

- CHANGELOG.md
- src/loaders/anndata-loaders/BaseAnnDataLoader.js
- src/loaders/anndata-loaders/CellsZarrLoader.js
If an AnnData store cell set ID's are not strings, there is no categorical value to be used.  Also I fixed a small bug in the factors display from when I was using dots and not slashes.  To test out here is an AnnData store and a [link](http://localhost:3000/?url=data:,{%22version%22:%20%221.0.0%22,%22name%22:%20%223ac0768d61c6c84f0ec59d766e123e05%22,%22datasets%22:%20[{%22uid%22:%20%2240334a99-2be7-4904-bc75-102609fe53e9%22,%22name%22:%20%2240334a99-2be7-4904-bc75-102609fe53e9%22,%22files%22:%20[{%22type%22:%20%22cells%22,%22fileType%22:%20%22anndata-cells.zarr%22,%22url%22:%20%22http://127.0.0.1:8081/R001_X005_Y003-anndata.zarr/%22,%22options%22:%20{%22poly%22:%20%22obsm/poly%22,%22xy%22:%20%22obsm/xy%22,%22factors%22:%20[%22obs/K-Means%20[Mean]%20Expression%22,%22obs/K-Means%20[Covarian …
> Fix Categories Parsing in AnnData and Factors Display

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/data-hooks.js
- src/components/spatial/utils.js
- src/loaders/RasterJsonLoader.js
- src/schemas/raster.schema.json
Begins to address #848.  The physical size scaling will be automatically detected and implemented if `usePhysicalSizeScaling` is provided and `true` in the `raster.json` - otherwise it will not be used.  With this default behavior, I think we should be able to maintain backwards compatibility.  What I mean by this is that going forward, we may want to decompose incoming transformations into scale, rotate, and translate and inject physical size scaling into those matrices.  Thus, with the `usePhysicalSizeScaling` as a parameter that needs be specifically passed in and `true` (without being required), people using transformation matrices but not `usePhysicalSizeScaling` won't automatically at some point in the future (if we implement it) have their matrices altered because we want to do …
> Physical Size-based Scaling

- CHANGELOG.md
- package.json
- src/layers/selection-utils.js
I think this fixes #854 using https://deck.gl/docs/api-reference/extensions/data-filter-extension
The only thing was that I had to remove `mixFunction` although I didn't notice a difference without it and previous to this PR with it.  I don't really understand why it is no longer needed, but presumably this has to do with how the new filtering process works.  To see the improvement in speed, use one of the big slide-seq examples I sent in the Vitessce chat last week and the difference should be considerable when compared with the links I shared for changing genes.
> DataFilterExtension for Selections

- CHANGELOG.md
- TESTING.md
- src/schemas/config.schema.json
Fixes a bug from #867 where the coordination type can be null.  Also adds a note to the testing docs that we should be checking the schema validity as we go.
To see this bug in action, add `debug=true` to vitessce.io or the most recent commit in this repo, and the Linnarsson example will throw an error about the schema.  This PR should fix it.
I want to merge this before #884 so I can test it properly.
> Fix Schema Bug from Auto-Centering

- CHANGELOG.md
- src/components/scatterplot/Scatterplot.js
- src/components/spatial/Spatial.js
Because `makeDefaultGetCellIsSelected` create a function where `cellSelection.includes` is called on every iteration over the cells, that can be very costly for large amounts of cells, which especially is noticeable at initial load time when things like concave hull, channel stats etc. are being calculated.  Furthermore, usually, the initial load is of the full cell set.  This PR makes it so that `null` is passed in to `makeDefaultGetCellIsSelected` which in turn causes the returned function not to call `cellSelection.includes` allowing us to speed up initial load time (and other interactions).
See https://github.com/vitessce/vitessce/pull/874/files#diff-e1ffdb1efb8675d0702711de4c2b151e39b9fc60e234489dfa0267d22c4f4c10R101-R102 from #874 for the original idea.
Here is a [demo …
> Don't Filter when All Cells are Selected

- CHANGELOG.md
- src/loaders/anndata-loaders/BaseAnnDataLoader.js
If the original `obs` key is a number, the categories may have identical datatype written in the `.zarray` in which case they are identical to the original values and a) do not need to be parsed and b) are not strings so should not have `getFlatTextArr` called on them.
Original idea from #874 at https://github.com/vitessce/vitessce/pull/874/files#diff-c17600274a959e1fd9266918de0c9088d723badfb408b1c8ec1d55d6f587171eR75-R80 (which was wrong - it should have been getting `.zarray` not `.zattrs`)
Here is a [demo merging](https://s3.amazonaws.com/vitessce-data/demos/2021-03-15/e4fec9d/index.html?url=data%3A%2C%7B+++%22version%22%3A+%221.0.0%22%2C+++%22name%22%3A+%223ac0768d61c6c84f0ec59d766e123e05%22%2C+++%22datasets%22%3A+%5B+++++%7B+++++++%22uid%22%3A+%2240334a99-2be7-4904-bc75-102609fe53e9%2 …
> Fix Bug in AnnData Categories Parsing

- CHANGELOG.md
- src/components/description/DescriptionSubscriber.js
Without this change, the Linnarsson example is broken because `format` is actually called even though it may not exist.  Didn't know `?` worked that way.
> Fix `format` Bug on Image Metadata.

- CHANGELOG.md
- src/app/Vitessce.js
- src/app/styles.js
- src/components/layer-controller/ChannelController.js
- src/components/layer-controller/LayerOptions.js
- src/components/layer-controller/VectorLayerController.js
- src/components/layer-controller/styles.js
- src/components/shared-plot-options/CellColorEncodingOption.js
This is a PR into your PR #903. In this I added the `useCheckboxStyles` to target the rule to the `input` element within the `<Checkbox />` component. I also wrapped the `<VitessceGrid` component with `ScopedCssBaseline` from MUI which hopefully will prevent future issues if people try to embed the Vitessce component into apps with global non-specific CSS rules (besides `rem` units which are trickier https://github.com/vitessce/vitessce-python/pull/57#issuecomment-808510301).
The switch from `<Select native` to `<NativeSelect` is not really necessary, but I noticed that it was recommended by MUI while I was looking into the other issues. https://material-ui.com/api/native-select/
https://github.com/vitessce/vitessce-python/pull/57 goes along with this.
> Add ScopedCssBaseline, update important height style

- CHANGELOG.md
- cypress/integration/vitessce.spec.js
- cypress/support/index.js
- package-lock.json
- package.json
- src/schemas/config-1.0.1.schema.json
There is a bug in raster schema I discovered while doing release testing.  `type` does not have to be (nor does it really make sense for it to be) `raster` on `spatialRasterLayers`.  Instead I had started to use that to mark the type of loader easily:
https://github.com/vitessce/vitessce/blob/8704222103a573f1e956377f8785b440f4ed7c97/src/components/spatial/utils.js#L225
I actually don't think this is used anywhere, but it is helpful for debugging.  We could also remove it and upgrade the schemas again.
I also added automatic schema validation to the cypress tests as another line of defense, because clearly I can't be counted on to read my own testing instructions :)
> Fix Raster Schema Bug

- CHANGELOG.md
- src/components/layer-controller/RasterLayerController.js
- src/components/layer-controller/styles.js
I'm not sure if this is the best solution, but with the layer closed the functionality of the slider seemed unclear, so this PR adds a label to your PR.
Maybe in the future a photoshop-like interface in the closed state would be even more compact
> Opacity Slider for Closed LayerController - addition of label

- CHANGELOG.md
- src/components/sets/CellSetExpressionPlot.js
Fixes #922.  
The 7 and the 50 come from experimenting but both seem to work very well, both for long and short labels.  I tried fiddling around with vega's "auto sizing" but couldn't really get it going and I'm not an expert in Vega.  If this isn't perfect, it does seem like an improvement.
For example, you can now see the "Cell Set" label in the Linnarsson example for the longer labels:
whereas previously you could not:
Also, now the small labels fill the space:
whereas previously they did not:
Here's the difference for the example from the portal:
> Violin Plot Styling

- CHANGELOG.md
- src/components/sets/CellSetExpressionPlot.js
Follow up to #924 after noticing an issue on the [Satija demo dataset](https://s3.amazonaws.com/vitessce-data/demos/2021-05-07/748cb9b/index.html?url=data:,%7B%22version%22:%20%221.0.1%22,%22name%22:%20%22Human%20Fetal%20Development%22,%22datasets%22:%20%5B%7B%22uid%22:%20%22human-fetus%22,%22name%22:%20%22Human%20Fetal%20Development%22,%22files%22:%20%5B%7B%22type%22:%20%22cells%22,%22fileType%22:%20%22anndata-cells.zarr%22,%22url%22:%20%22https://azimuth-vitessce.s3.us-west-2.amazonaws.com/human-fetus/vitessce_ref.zarr%22,%22options%22:%20%7B%22mappings%22:%20%7B%22UMAP%22:%20%7B%22key%22:%20%22obsm/X_umap%22,%22dims%22:%20%5B0,1%5D%7D%7D,%22factors%22:%20%5B%22obs/annotation.l1%22,%22obs/annotation.l2%22,%22obs/organ%22%5D%7D%7D,%7B%22type%22:%20%22cell-sets%22,%22fileType%22:%20%22annd …
> Fix Margin Bottom for Violin Plot (Again)

- CHANGELOG.md
- src/components/spatial/SpatialSubscriber.js
- src/components/spatial/utils.js
Fixes #937
This PR does two things to fix the issue:
1. If there is a raster image, use it for the initial view state.  This is to prevent the image from looking "punched in" when there are fewer cells like: https://portal.hubmapconsortium.org/browse/dataset/243bf6ec414b3e16695bef1e97809b61 (R001_X003_Y001)
2. If there is only one cell (or colinear cells on either axis), use the polygon bounds to determine the initial view state
> Fix Cell/Raster Initial View State

- CHANGELOG.md
- src/components/spatial/Spatial.js
Another bug caught during release testing.  The cell colors can have opacity as well it appears but we don't use that information when creating the lookup texture for colors for the cells in the bitmask.
> Fix `cellColors` Assumed to be RGB (Can be RGBA)

- CHANGELOG.md
- src/components/layer-controller/LayerControllerSubscriber.js
- src/components/spatial/Spatial.js
- src/components/spatial/SpatialSubscriber.js
Bug caught while doing release testing.
Previously the `cells` layer would show after the `bitmask` had been removed and the lasso was not showing properly, both because they relied on the `bitmask` layer being present - however that is not always true.  Thus instead we rely on the layer raster metadata for detecting `bitmask` presence so that even if it isn't loaded, it is still detected
> Fix Condition for Displaying Cells Layer

- CHANGELOG.md
- src/components/shared-spatial-scatterplot/AbstractSpatialOrScatterplot.js
Another bug caught during release testing.
Show the lasso if there is `cellsEntries` data with centroids or there is a `cellsLayer`.  I actually am not so sure about the correctness here - it seems like if there are just polygon coordinates and no centroids, there should be no selection option because selection relies on centroids at the moment.
Also the `findIndex` result should be greater than __or equal__ to 0 not just greater than (since not-found returns -1, not 0).
> Fix Lasso Display Bug for Centroids.

- CHANGELOG.md
- src/components/layer-controller/LayerControllerSubscriber.js
Found a bug while doing release testing for #939.  If you remove and then re-add (or just add) an image layer with the current demo in #939, it will always add a `bitmask` controller instead of `raster` regardless of the actual image.  This should be the fix for that.
> Fix `bitmask` Layer Add/Remove Bug

- CHANGELOG.md
- src/components/shared-spatial-scatterplot/quadtree.js
Fixes a bug where scatterplots alone i.e `cells.json` without `xy` centroids don't work.
> Fix Quadtree Condition Bug

- CHANGELOG.md
- src/Pool.js
- src/components/heatmap/Heatmap.js
- src/components/heatmap/HeatmapWorkerPool.js
- src/components/heatmap/Pool.js
- src/components/heatmap/heatmap.worker.js
I think this fixes #934.
This PR:
- Adds a generic pool class that could be re-used for whatever need arises by implementing the `process` function.
- A specific pool implementation for the heatmap tiles that is used by the `Heatmap` component.
- Fixes a small bug where `xTiles` and `yTiles` had not been calculated yet but `expression` had been, which sets off one round of processing, but then `xTiles` and `yTiles` are calculated setting off duplicated processing
There should be a noticeable difference for example with the [recent neocortex example](http://localhost:3000/?url=https://second-trimester-neocortex.s3.amazonaws.com/Temporal_gw20/vitessce_config_Temporal_gw20.json) or with [the satija example from the portal](http://localhost:3000/?url=data%3A%2C%7B+++%22version%22%3A+%220.1.0%2 …
> Worker Pool for Heatmap

- CHANGELOG.md
- src/components/layer-controller/LayerController.js
- src/components/layer-controller/VectorLayerController.js
- src/components/layer-controller/styles.js
For whatever reason, `makeStyles` wasn't overriding the styles from the default MUI classes. Switching to `useStyles` for the affected components fixes the issue. A lot of people seem to experience these issues with the styling libraries provided by MUI, apparently they are moving away from the libraries in their new major version to styled-components/emotion.
The sections also weren't completely aligned in the previous version. 'Molecules' and 'Cell Segmentations' sections had a total of `18px` horizontal padding on each side whereas the 'Image' section had `16px`, so I fixed that.
Hope this helps!
> John conroy/fix controller styles

- CHANGELOG.md
- src/loaders/anndata-loaders/BaseAnnDataLoader.js
This PR fixes two issues introduced by #948 noticed during #939:
1. We removed the `TypedArray` merging on `data` which needs to use different APIs (specifically the `matrixGenesFilter` uses these `TypeArray`s as opposed to arrays of strings)
2. Check the need for using `VLenUtf8` more robustly
I think you can test the problem/fix with ```data:,{"coordinationSpace":{"dataset":{"A":"A"},"embeddingType":{"A":"UMAP"}},"datasets":[{"files":[{"fileType":"anndata-cells.zarr","options":{"factors":["obs/marker_gene_0","obs/marker_gene_1","obs/marker_gene_2","obs/marker_gene_3","obs/marker_gene_4"],"mappings":{"UMAP":{"dims":[0,1],"key":"obsm/X_umap"}}},"type":"cells","url":"https://assets.hubmapconsortium.org/277152f17b5a2f308820ab4d85c5a426/hubmap_ui/anndata-zarr/secondary_analysis.zarr"},{"fileT …
```
> Fix `VLenUTF8` Filter Check + Concat Typed Arrays

- CHANGELOG.md
- src/components/scatterplot/ScatterplotSubscriber.js
This PR switches the `cellSetPolygonCache` to use an array of tuples, since when it was an object, the keys `[["Leiden", "0"], ["Leiden","1"], ["Leiden","2"]]` get converted to strings like `"Leiden,0,Leiden,1,Leiden,2"`.
> PR into Lazy Load Scatterplot Polygons PR

- CHANGELOG.md
- src/components/layer-controller/LayerController.js
Follow up from our discussion from yesterday about what to do with multiple 3D layers.  This adds an "eye" icon next to the layer name in the controller.
> Add Global Visibility Button.

- CHANGELOG.md
- src/components/layer-controller/BitmaskChannelController.js
Fixes #958.
The diff looks like more but I just removed the `width: 100%` off the grid as well as the unnecessary column grid and then padded the button correctly.
Before:
After:
> Fix Bitmask Removal Button Overflow 

- CHANGELOG.md
- src/loaders/anndata-loaders/BaseAnnDataLoader.js
This PR does a bit of refactoring and hopefully speeds thing up by letting the requests/decoding go off truly asynchronously.
> Clean up `getFlatArrDecompressed`

- CHANGELOG.md
- src/components/sets/CellSetExpressionPlot.js
- src/components/sets/CellSetExpressionPlotSubscriber.js
When user activates log-transform, the Y axis title in the violin plot will now change to indicate the transformation (see issue [#902](https://github.com/vitessce/vitessce/issues/902)).
As you can see, there are currently two versions for the Y axis in the code. I'm torn between "Log-Normalized Expression Values" and "Log-Transformed Normalized Expression Values". Since even the shorter of these two labels is borderline long, I split the longer one in two lines. Personally, I prefer the two-line solution, but ultimately it depends on the layout, with either the X or the Y axis being more limiting.
> Add "log" label to CellSetExpressionPlot when log-transform is active

- CHANGELOG.md
- src/components/layer-controller/LayerController.js
- src/components/spatial/Spatial.js
- src/components/spatial/constants.js
- src/schemas/config-1.0.1.schema.json
Fixes #967 by separating channel visibility from "global" visibility even though there is no such prop in Viv.
> Add Global Visibility per Raster Layer

- CHANGELOG.md
- src/components/layer-controller/LayerController.js
- src/components/layer-controller/LayerOptions.js
Request from Nils
- Don't show the tabs at all when 3D is not available (disabled or no z-stack)
- Don't show dropdown if 3D is disabled.
> Don't Show Any 3D UI When not Available

- CHANGELOG.md
- src/components/hooks.js
- src/components/layer-controller/LayerControllerSubscriber.js
This is a PR into #979 since it should also respond to window resizes, and this also should prevent from running the `.closest` on every LayerController render.
> Add a custom hook and listen for window size changes

- CHANGELOG.md
- package-lock.json
- package.json
- src/loaders/anndata-loaders/BaseAnnDataLoader.js
Upgrading zarr.js gets rid of the 404's for `.zgroup`: https://github.com/gzuidhof/zarr.js/pull/73 (it also causes the compressor to be a Promise because of https://github.com/gzuidhof/zarr.js/pull/63 I think)
> Upgrade zarr.js

- CHANGELOG.md
- package-lock.json
- package.json
- src/loaders/anndata-loaders/BaseAnnDataLoader.js
- src/loaders/anndata-loaders/CellSetsZarrLoader.js
- src/loaders/anndata-loaders/CellsZarrLoader.js
This is just something I noticed that could be better - we shouldn't need to create the data structures every time `load` is called so this caches those computations.
> Cache Data Structures on `AnnData` Loaders

- CHANGELOG.md
- src/app/view-config-upgraders.js
- src/schemas/config-1.0.2.schema.json
Following up on [my comment](https://github.com/vitessce/vitessce/pull/1001#issuecomment-882767563) I think it may actually make more sense to just remove this `type` part of the schema altogether during the schema upgrade.  Do you see any value to either leaving it as-is without this PR or enforcing the type?  The information seems redundant so removing it would make things cleaner.
> Enforce Spatial Raster Type

- CHANGELOG.md
- src/app/vitessce-grid-utils.js
- src/loaders/AbstractTwoStepLoader.js
- src/loaders/GenomicProfilesZarrLoader.js
- src/loaders/MatrixZarrLoader.js
- src/loaders/OmeZarrLoader.js
- src/loaders/anndata-loaders/BaseAnnDataLoader.js
- src/loaders/anndata-loaders/CellSetsZarrLoader.js
- src/loaders/anndata-loaders/CellsZarrLoader.js
- src/loaders/anndata-loaders/MatrixZarrLoader.js
- src/loaders/anndata-loaders/MatrixZarrLoader.test.js
- src/loaders/anndata-loaders/index.js
- src/loaders/data-sources/AnnDataSource.js
- src/loaders/data-sources/AnnDataSource.test.js
- src/loaders/data-sources/ZarrDataSource.js
- src/loaders/data-sources/index.js
- src/loaders/types.js
A different approach to #997 (without a schema change).
Rather than relying on inheritance for the derived AnnDataLoaders, we can have a two step process that creates a *base loader* (`BaseAnnDataLoader`), and then the subsequent loaders are constructed with `baseLoader` as the arguments instead of `file`.
I think this provides a natural way to share behavior (and caching) among derived loaders. The `baseLoader` defines all shared behavior and a "standard" interface for all derived dataloaders. We can cache the `baseLoader` by URL, meaning that files with the same URL end up with the same `baseLoader`.
~This PR is a rough sketch, and I might have missed some conversions of `this` -> `this.baseLoader` in the derived loaders. I'd rather open for discussion first before moving ahead!~
Should …
> Two-step dataloaders for AnnData

- CHANGELOG.md
- package-lock.json
- package.json
The scATAC demo currently fails to load because `higlass-zarr-datafetchers` uses zarr via peer dependency and was never updated to account for the `supportedMethods` option in zarr.js `0.3.1`.
> Upgrade higlass zarr datafetchers to 0.2.1

- .github/pull_request_template.md
- CHANGELOG.md
I think we should start making sure the R and Python packages keep pace with this package.  They don't have to follow the same release schedule but they should be always-deployable in some sense with the latest Vitessce.  I'm open to other suggestions but I feel like requiring this at the time of the main vitessce PR is helpful (and also forces you test the PR in a different environment).  I can close though if we don't agree.
> PR Template

- CHANGELOG.md
- src/components/scatterplot/ScatterplotSubscriber.js
- src/components/spatial/SpatialSubscriber.js
For https://github.com/vitessce/vitessce/pull/1052#issuecomment-924217982
- Fix default values not provided after upgrading deck.gl
> Use Correct Default Values for Schema When None Provided

- CHANGELOG.md
- src/components/layer-controller/LayerController.js
#1037 seems to have introduced a consistency issue of its own.  This PR resolves that by not using the `ref` for operations that don't need it because the `ref` and `channels` appear to be off by "one frame".  So when you remove a channel, it appears in `channels` before the `ref`.
- Fix usage of the channels ref.
>  Fix Channel Removal and Addition from #1037 

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/CallbackPublisher.js
- src/app/Vitessce.js
- src/app/VitessceGrid.js
- src/app/VitessceGrid.test.js
- src/app/state/hooks.js
- src/components/layer-controller/LayerControllerSubscriber.js
Fixes #1057 
Towards https://github.com/vitessce/vitessce-python/issues/29
- Uses zustand `createContext` with store creation functions to set up independent zustand stores for each `<Vitessce/>` component instance, rather than using global stores, which causes unintended sharing of state when there are multiple `<Vitessce/>` components on the same page.
> Contexts for zustand stores

- CHANGELOG.md
- src/loaders/anndata-loaders/CellSetsZarrLoader.js
In the production build of the documentation site, the minified code has compiled `Array(...new Set(x))` to `Array.apply(void 0, new Set(x))`, which results in the array being `[]` despite the set having 6047 elements (15 unique). 
I thought the underlying issue may be with babel so I tried setting [`iterableIsArray: false`](https://babeljs.io/docs/en/assumptions#iterableisarray) in the babel assumptions but that broke the build further.
> Fix set spread syntax bug

- CHANGELOG.md
- src/components/sets/cell-set-utils.js
Fixes #1105 
The function to initialize cell set colors upon loading `cell-sets.json` files was not considering user-provided colors.
> Fix cell set color bug

- CHANGELOG.md
- README.md
Started as a little edit to make the documentation link more prominent. Also:
- Make the screen shots smaller and side-by-side.
- Copy over the main selling points from vitessce-io.
- direct link to the sandbox. (Is that the right name?)
- Drop the section about configs embedded in data-uri: It's a bit scary, and it's really only pertinent to the sandbox.
> revise readme

- CHANGELOG.md
- docs/docs/components.mdx
- docs/docs/roadmap.mdx
- docs/sidebars.js
I wanted to make it more clear to users (or prospective users) about the current state of major planned or in-progress features. I also started to update the docs to use the term "view" rather than "component" since I think "view" is more clear in the view config context, while "component" is more clear in the React / development context.
- Add a roadmap page to the documentation site.
> Add roadmap to documentation

- CHANGELOG.md
- src/components/heatmap/Heatmap.js
- src/components/heatmap/heatmap.worker.js
- src/components/heatmap/utils.js
- src/components/heatmap/utils.test.js
A lot of the time spent on the workers for the heatmap is just calling `indexOf` so this speeds things up quite a bit.  It's still not as fast as #1151 but #1151 might be too complicated (i.e not worth committing) in light of the not-so-bad performance here.
- Usa a hash table lookup instead of calling `indexOf` repeatedly for the heatmap.
> Lookup Table for Heatmap Tiling

- CHANGELOG.md
- docs/docs/data-file-types.mdx
- docs/docs/view-config-json.md
- src/api/VitessceConfig.js
- src/app/view-config-upgraders.js
- src/loaders/anndata-loaders/CellSetsZarrLoader.js
- src/loaders/anndata-loaders/CellsZarrLoader.js
- src/loaders/data-sources/AnnDataSource.js
- src/loaders/data-sources/AnnDataSource.test.js
- src/schemas/config-1.0.7.schema.test.js
- Makes the `loadVariable` more general to support more than obs and var dataframes (such as `uns/my_col` for example)
- Documentation for the `geneAlias` property
> PR into var_alias PR

- CHANGELOG.md
- package.json
- scripts/build-demo.js
- scripts/karma.config.js
- scripts/start-demo.js
- scripts/webpack.config-common.js
- scripts/webpack.config-demo.js
- scripts/webpack.config-lib.js
It can be helpful to disable linting when quickly prototyping code or making a lot of changes before cleaning up when ready to make a PR.
- Adds the script `npm run start:nolint` which disables linting.
> `npm run start:nolint` script

- .github/workflows/deploy.yml
- CHANGELOG.md
- set-node-options.sh
v1.2.0 and v1.2.1 did not deploy via github actions:
- https://github.com/vitessce/vitessce/runs/8122998915?check_suite_focus=true
- https://github.com/vitessce/vitessce/runs/7505874619?check_suite_focus=true
due to `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory` during `npm run build-lib:prod` which runs as part of `npm publish`
This updates the deployment scripts to increase the memory for node and also re-enables the publish errors
> Update set-node-options script

- .github/workflows/deploy.yml
- CHANGELOG.md
- check-deploy.sh
- create-release.sh
I recently removed the `continue-on-error` line (https://github.com/vitessce/vitessce/pull/1323) from the deploy step because it was hiding true deployment errors. I had forgotten that the reason it was needed in the first place was because when `npm publish` is run on a non-release-PR it throws an error (because NPM (rightly) does not allow publishing the same package twice with the same version number).
> Fix deploy CI again

- CHANGELOG.md
- packages/view-types/spatial/src/Spatial.js
Fixes #1341.  I think the issue highlights why we need to do this (we did do this for a while, must have been a regression when we refactored to Viv extensions since this functionality no longer lived in the core of the `MultiscaleImageLayer`)
- Make sure to exclude the background image when using "Zero Transparent" feature.
> (fix): Exclude background with "Zero Transparent"

- CHANGELOG.md
- packages/vit-s/src/VitS.js
Fixes the case in which multiple instances of Vitessce on the same page try to use the same `.jss-X` class name to style different elements.
> Make MUI class names deterministic

- CHANGELOG.md
- packages/file-types/zarr/src/anndata-loaders/FeatureLabelsAnndataLoader.js
- packages/file-types/zarr/src/anndata-loaders/ObsEmbeddingAnndataLoader.js
- packages/file-types/zarr/src/anndata-loaders/ObsLabelsAnndataLoader.js
- packages/file-types/zarr/src/anndata-loaders/ObsLocationsAnndataLoader.js
- packages/file-types/zarr/src/anndata-loaders/ObsSegmentationsAnndataLoader.js
I noticed that the `combat` example was loading slowly in 2.0.1 and I think this is part of the reason.  I'm gonna try a few little improvements beyond just this to speed up loading but this is definitely a start.
- Cache the promise not the payload of the AnnData loaders
> (fix): Cache promises, not payloads, in `AnnData` loaders

- CHANGELOG.md
- packages/file-types/zarr/src/anndata-loaders/ObsSegmentationsAnndataLoader.js
- packages/view-types/spatial/src/Spatial.js
Fixes #1366 
- Casts polygon vertices to `Array` as workaround for what seems to be a DeckGL v8.8 bug
> Fix polygon bug

- CHANGELOG.md
- sites/html/src/es.html
- sites/html/src/es.min.html
unpkg is throwing `Internal Server Error` for `es-react` https://unpkg.com/browse/es-react@16.13.1/
- Use react via `esm.sh` CDN instead
> Use esm.sh react

- CHANGELOG.md
- packages/view-types/obs-sets-manager/src/styles.js
Fixes the weird styles that were identified in this PR https://github.com/vitessce/vitessce-python/pull/210#pullrequestreview-1226334322
which comes from the classic Jupyter Notebook interface using CSS that was more specific than the vitessce CSS. The important modifier should fix this.
> Jupyter notebook style fixes

- CHANGELOG.md
- tsconfig.json
With the TS Project References enabled, this extra flag is required in order to use the Go To Definition (command+click) in vscode. Otherwise when you command+click, vscode will take you to the generated code within `dist-tsc/` rather than `src/` where you want to go.
Related to https://github.com/microsoft/TypeScript/issues/49003#issuecomment-1164655018 and https://github.com/microsoft/TypeScript/issues/6209
> Fix Go to Definition support

- CHANGELOG.md
- packages/config/src/VitessceAutoConfig.js
When I was testing something else using the zero config mode functionality, I noticed that there is no coloring on my cell sets. The coloring was missing, because the cell sets information is kept in obs/Subcluster, which is not a field that we were checking for. 
- Added one more value called "subcluster" under `supportedObsSetsKeys`
> Fixed a bug, where subcluster path is not added to obsSets and coloring of sets does not appear.

- CHANGELOG.md
- packages/gl/src/BitmaskLayer.js
- packages/utils/other-utils/src/interpolate-colors.js
- packages/view-types/heatmap/src/HeatmapSubscriber.js
- packages/view-types/scatterplot-embedding/src/EmbeddingScatterplotSubscriber.js
- packages/view-types/scatterplot-gating/src/GatingSubscriber.js
- packages/view-types/scatterplot/src/Scatterplot.js
- packages/view-types/spatial/src/Spatial.js
- packages/view-types/spatial/src/SpatialSubscriber.js
Fixes #1509 
I closed a PR with a larger set of changes https://github.com/vitessce/vitessce/pull/1510 in favor of this one which seems to resolve the issue without the need to move logic to worker which got messy very fast.
Use `compare: false` for `expressionData` and `cellColorData` props in `BitmaskLayer`. Instead, provide corresponding keys that can be compared rather than the arrays themselves.
Ideally, the arrays could just be compared shallowly (without the need for the key business), but it seems like the only options are `true`/`false`, though maybe i am missing something.
I also removed some outdated logic from the `getCellColors` function, as the mapping from expression values to colors does not use the `cellColors` `Map` variable anymore - that is performed on the GPU by …
> Do not deep compare large arrays in BitmaskLayer props

- CHANGELOG.md
- sites/docs/docs/about.md
In a previous PR, I moved the Showcase to a standalone page in the documentation but forgot to remove that section from the About page.
(Change that I originally made in https://github.com/vitessce/vitessce/pull/1519 but have reverted there to make an independent PR since it was unrelated)
> Remove Showcase from About page

- .eslintrc.yml
- .meta-updater/main.mjs
- CHANGELOG.md
- packages/view-types/description/package.json
- packages/view-types/feature-list/package.json
- packages/view-types/heatmap/package.json
- packages/view-types/scatterplot/package.json
- packages/view-types/status/package.json
- packages/vit-s/package.json
- pnpm-lock.yaml
Fixes https://github.com/vitessce/vitessce/issues/1546
In https://github.com/vitessce/vitessce/pull/1441 I removed `airbnb` from the eslint config because I thought it was related to eslint issues with TypeScript but want to revert that change. 
- Revert change that removed `airbnb` eslint config.
- address extraneous dependency warnings to fix the linked issue.
> Revert change that removed airbnb eslint config

- CHANGELOG.md
- packages/file-types/json/src/json-loaders/ObsSetsJson.js
- packages/utils/sets-utils/src/io.js
- packages/utils/sets-utils/src/set-path-utils.js
- packages/view-types/obs-sets-manager/src/ObsSetsManagerSubscriber.js
- packages/view-types/statistical-plots/src/CellSetSizesPlotSubscriber.js
Fixes bug reported by @ivababukova  on [slack](https://hms-dbmi.slack.com/archives/GG50HSQ4E/p1685094853061079) plus two others
- Only set `additionalObsSets` in coordination space when upgrade was necessary to prevent infinite loop.
- Introduced in https://github.com/vitessce/vitessce/pull/1529 / https://github.com/vitessce/vitessce/pull/1441
- Fix bug causing cell set hierarchy created via `Create hierarchy` button to contain the string `undefined` (e.g., `My hierarchy 1undefined`)
- Fix bug in `CellSetSizesPlotSubscriber` causing page to crash when no `obsSets` view is present (due to expectation of initialized `obsSetSelection` and `obsSetExpansion` coordination values).
> Fix cell set bugs

- CHANGELOG.md
- packages/view-types/heatmap/src/Heatmap.js
- packages/view-types/heatmap/src/HeatmapSubscriber.js
Discovered while testing the release PR v3.0.0 with portal-ui
Highlights and selections of obs/features are assumed to be in terms of obsIndex/featureIndex values. 
I did not catch this when reviewing the heatmap click implementation in #1479 but discovered while testing with portal configs like https://portal.hubmapconsortium.org/browse/dataset/6b5d4d3a6af69a3bb82c4768cd24396c.vitessce.json that if featureLabels were present, those were being used for the featureHighlight value, causing the incorrect gene to be selected.
-
> Fix heatmap click bug when featureLabels are used

- CHANGELOG.md
- packages/view-types/scatterplot-embedding/src/EmbeddingScatterplotSubscriber.js
- packages/view-types/scatterplot/src/Scatterplot.js
- packages/view-types/spatial/src/Spatial.js
When testing https://github.com/vitessce/vitessce/pull/1542 with the `satija-2020` demo  I noticed that clicking the recenter button caused a crash - it seems like because the view config defines initial values for the embedding target and zoom, causing originalViewState to not be set as expected. 
- Set originalViewState in all cases, including when it is not automatically computed
- Add extra checks in the recenter function
> Fix bug with originalViewState

- CHANGELOG.md
- packages/utils/spatial-utils/src/spatial.js
From #1484, the returned object from `unit` i.e., `sizes[0]` is a special `Units` object with its own equality method.  If we don't use this, we will always assume that height and width are different when they aren't.  We need to `equals` in order to actually compare the values: https://mathjs.org/docs/datatypes/units.html
- Use `equals` instead of `==` for comparing `Units`
> (fix): equality check for `sizes`

- CHANGELOG.md
- packages/view-types/scatterplot-embedding/src/EmbeddingScatterplotSubscriber.js
Fixes safari-related issue found during testing of #1548 
I could reproduce with the localhost demo, but not consistently. Slowing down my computer by opening in multiple safari windows seemed to help reproduce the bug.  I think it has to do with the react-grid-layout animation not being finished, resulting in the `width` and `height` used in the initialization calculation being too low because the views are still animating larger.
I think this fixes the bug you found @ilan-gold - it is not an ideal way to fix it but more of a hack.
I think the ideal fix would be to implement a way to retrieve "initial" coordination values from the view config, possibly leveraging the new `config.uid` property for hinting about initialization vs. interactions. Then we could always re-compute things based …
> Fix for safari bug resulting in bad scatterplot initialization

- CHANGELOG.md
- packages/utils/sets-utils/src/set-path-utils.js
- packages/utils/sets-utils/src/set-path-utils.test.js
- packages/view-types/statistical-plots/src/CellSetSizesPlotSubscriber.js
Fixes #1558 
When there is no `obsSets` view, the `obsSetSizes` bar plot does not render anything anymore. This is because we compute the paths to show in the `CellSetSizesPlotSubscriber` only if `cellSetExpanded` is not null. `cellSetExpanded` is null when there is no `obsSets` view.
- Made `CellSetSizesPlotSubscriber` compute the bars to show even when `cellSetExpanded`.
- Changed the `filterPathsByExpansionAndSelection` function to not rely on `cellSetExpanded` always being defined.
TODOs:
> Show paths in current hierarchy when cellSetExpanded is not defined

- CHANGELOG.md
- packages/vit-s/src/hooks.js
Fixes #1608
The helpdesk received a ticket where a user was confused about duplicate download link entries were appearing for various datasets in HuBMAP:
I reproduced this in the vitessce demo site here:
http://vitessce.io/#?edit=false&url=https%3A%2F%2Fportal.hubmapconsortium.org%2Fbrowse%2Fdataset%2F69d9c52bc9edb625b496cecb623ec081.vitessce.json
I traced the calculation and confirmed this was happening due to two lists having the same entries. Due to objects not working with `SameValue` comparison, `Set` didn't work for deduplication, so I performed the comparison by making sure the index of each URL in the array matched the return of the `findIndex` for a URL with the same `name` parameter (which filters out any instances of URL's with the same name after the first).
After the fix/with …
> #1608 Add handling to filter duplicate names from download options

- .changeset/few-actors-act.md
- packages/vit-s/src/VitS.js
Fixes #1616 
- There is an issue on the HuBMAP data portal where switching between different view configs for the visualization causes a black screen to be displayed
- After doing some digging, I found that the image layers were not being properly reinitialized when the config key/the callback used to generate the store changed; no image loading requests were taking place, and the Spatial layer display was `null`.
- In order to force the store to be recreated when the provided config is changed, the `configKey` can be provided to the `ViewConfigProvider` component as a `key`; when the `key` changes, [React unmounts and remounts the provider, which regenerates the store and ensures that](https://react.dev/learn/preserving-and-resetting-state#option-2-resetting-state-with-a-key) …
> Regenerate View Config store on `configKey` change

- packages/view-types/layer-controller/src/BitmaskChannelController.js
- packages/view-types/layer-controller/src/ChannelOptions.js
- packages/view-types/layer-controller/src/ColorPalette.js
- packages/view-types/layer-controller/src/LayerController.js
- packages/view-types/layer-controller/src/LayerOptions.js
- packages/view-types/layer-controller/src/RasterChannelController.js
- packages/view-types/layer-controller/src/VolumeOptions.js
- packages/view-types/layer-controller/src/shared-channel-controls.js
- packages/view-types/scatterplot/src/ScatterplotOptions.js
- packages/view-types/scatterplot/src/shared-spatial-scatterplot/ToolMenu.js
- packages/vit-s/src/TitleInfo.js
- packages/vit-s/src/shared-mui/components.js
- packages/vit-s/src/shared-plot-options/OptionsContainer.js
- sites/docs/docs/tutorial-plugin-coordination-type.mdx
- Only MUI Slider supports getAriaLabel: https://v4.mui.com/api/slider/#props
- MUI components for MenuItem, IconButton, Button, Tabs, Tab, and Table do not support getAriaLabel
- These components pass extra props down to the corresponding native HTML element
- Native Select passes extra props down via `inputProps` prop https://v4.mui.com/api/native-select/#nativeselect-api
- React supports `aria-label` as a prop https://legacy.reactjs.org/docs/accessibility.html#wai-aria
- There were still periods in the label text
> Accessibility fixes

- sites/docs/src/css/custom.css
- sites/docs/src/pages/_Index.js
- sites/docs/src/pages/styles.module.css
This fixes the browser window resizing, updates the styles, only shows the expand button when in "demo mode", and initializes to expanded rather than collapsed for "edit mode".
This also changes to only using absolute and relative positioning, and removes the `transform: scaleY`.
> Fixes for expand buttons

- .changeset/giant-apricots-think.md
- examples/configs/src/index.js
- examples/configs/src/view-configs/visium-spatial-viewer.js
- packages/file-types/json/src/raster-json-loaders/RasterJsonAsObsSegmentationsLoader.js
- packages/view-types/spatial/src/SpatialSubscriber.js
Fixes #1668
I was able to reproduce by copying the config for Spatial Transcriptomics for AKI sample S-2002-007755 and using the debug mode. It appears that since the raster.json as obsSegmentations loader was returning `obsSegmentationsType === 'bitmask'` despite the obsSegmentations data being null, this if statement was evaluating to `true` and running when it should not, causing the crashing. https://github.com/vitessce/vitessce/blob/6762b9242eefb0b9bd28009384123ace4475994c/packages/view-types/spatial/src/SpatialSubscriber.js#L406
I also noticed that the pseudo-segmentation diamonds were not appearing due to the hasSegmentationsData only checking the existence of the loader. Here, I added an extra check that the data is non-null.
-
> Fix obsSegmentations.raster.json bugs

- examples/configs/src/view-configs/codex-oop.js
- examples/configs/src/view-configs/visium-polygons-oop.js
- packages/gl/src/BitmaskLayerBeta.js
- packages/gl/src/bitmask-layer-beta-shaders.js
- packages/utils/sets-utils/src/cell-set-utils.js
- packages/utils/sets-utils/src/index.js
- packages/view-types/spatial-beta/src/Spatial.js
- packages/view-types/spatial-beta/src/SpatialSubscriber.js
> Cell/obs set color support in spatialBeta view

- .changeset/yellow-tools-laugh.md
- .meta-updater/main.mjs
- packages/view-types/feature-list/package.json
- packages/view-types/feature-list/src/FeatureListOptions.js
- packages/view-types/heatmap/package.json
- packages/view-types/heatmap/src/HeatmapOptions.js
- packages/view-types/layer-controller-beta/package.json
- packages/view-types/layer-controller-beta/src/ChannelOptions.js
- packages/view-types/layer-controller-beta/src/ImageLayerController.js
- packages/view-types/layer-controller-beta/src/PointLayerController.js
- packages/view-types/layer-controller-beta/src/SegmentationChannelController.js
- packages/view-types/layer-controller-beta/src/SpotLayerController.js
- packages/view-types/layer-controller/package.json
- packages/view-types/layer-controller/src/LayerController.js
- packages/view-types/layer-controller/src/LayerOptions.js
- packages/view-types/scatterplot-embedding/package.json
- packages/view-types/scatterplot-embedding/src/EmbeddingScatterplotOptions.js
- packages/view-types/scatterplot-gating/package.json
- packages/view-types/scatterplot-gating/src/GatingScatterplotOptions.js
- packages/view-types/scatterplot/package.json
- packages/view-types/scatterplot/src/ScatterplotOptions.js
- packages/view-types/spatial/package.json
- packages/view-types/spatial/src/SpatialOptions.js
- packages/view-types/statistical-plots/package.json
- packages/view-types/statistical-plots/src/CellSetExpressionPlotOptions.js
- packages/vit-s/package.json
- packages/vit-s/src/shared-plot-options/CellColorEncodingOption.js
- pnpm-lock.yaml
Fixes #1686 
I did not realize useId was only introduced in React v18 (https://react.dev/blog/2022/03/29/react-v18#useid). To continue supporting v16 and v17 we cannot use this hook.
- Use the `useId` hook from `react-aria` package which has same functionality https://react-spectrum.adobe.com/react-aria/useId.html
> Use react-aria useId

- .changeset/five-geese-tan.md
- packages/file-types/zarr/src/genomic-loaders/GenomicProfilesZarrLoader.js
- packages/view-types/genomic-profiles/package.json
- packages/view-types/genomic-profiles/src/GenomicProfilesSubscriber.js
- packages/vit-s/src/data-hook-utils.js
- packages/vit-s/src/data/LoaderResult.js
- pnpm-lock.yaml
Fixes #1593 
The genomic profiles view failed to load data from sources which require an `Authorization` header; with this change, it is possible for the appropriate headers to be provided as part of a `requestInit` object like it is for other AnnData loaders.
- Bumped `higlass-zarr-datafetchers` to `0.3.0-next.3`
- Added `requestInit` support to the loader
> NickAkhmetov/Add support for `requestInit` in genomic profiles view

- .changeset/rare-mirrors-thank.md
- packages/view-types/spatial-beta/src/SpatialSubscriber.js
- packages/view-types/spatial-beta/src/SpatialTooltipSubscriber.js
This PR adds obsSets to tooltip for segmentations in the SpatialLayoutBeta component.
Fixes part of 1685 (Towards #1685 (obsSets in tooltips))
-
> Added ObsSets to tooltip for segmentations

- .changeset/small-adults-collect.md
- examples/configs/src/view-configs/spatial-beta/codex.js
- packages/constants-internal/src/constants.ts
- packages/file-types/zarr/src/spatialdata-loaders/SpatialDataObsSetsLoader.js
- packages/main/all/src/base-plugins.ts
- packages/schemas/src/file-def-options.ts
Fixes #
In https://github.com/vitessce/vitessce/pull/1811 I incorrectly used the object schema `{ obsSets: [] }`  instead of the array schema directly, causing the schema validation for spatialdata configs to fail. This PR fixes that issue
-
> Fix spatialdata file options bug

- .changeset/thick-tables-refuse.md
- packages/view-types/spatial-beta/src/SpatialSubscriber.js
Fixes #1965 
`obsSegmentationsData` was often turned `undefined` because it was not passed as a dependency to the `delegateHover` callback.
With this change, tooltips should appear whenever a cursor hovers a segmentation polygon in https://vitessce.io/#?dataset=codeluppi-2018-2.
> Fix tooltips in polygon segmentations for spatialBeta

- .changeset/lovely-papayas-shout.md
- packages/view-types/spatial-beta/src/Spatial.js
Fixes #2028
- Fixes bug where tooltips would not appear when mousing over the body of unfilled polygons/segments in a spatial beta component.
> Fix #2028 - Tooltip issue with spatial beta

- .changeset/slimy-scissors-work.md
- packages/utils/zarr-utils/package.json
- packages/utils/zarr-utils/src/normalize.ts
- pnpm-lock.yaml
Fixes issue with  http://localhost:3000/?dataset=visium-spatial-viewer  reported by @tkakar 
This was related to https://github.com/vitessce/vitessce/pull/2044 which pulled in https://github.com/manzt/zarrita.js/pull/212
We should separately look into the settings for the CloudFront deployment that is serving the data, maybe we can prevent the 403 errors there as well.
-
> Add relaxed fetchStore

- .changeset/mean-dryers-protect.md
- packages/vit-s/src/vitessce-grid-utils.js
This PR fixes a bug that i was encountering only on the production vitessce.io docs site.
It was due to the JS minification affecting the `DataSourceClass.prototype.constructor.name` strings, resulting in conflicting strings. These conflicting strings resulted in the wrong DataSourceClass being assigned to DataLoaders, causing errors such as methods not being found.
-
> Fix DataSource class name bug

- .changeset/empty-rocks-whisper.md
- examples/configs/src/view-configs/spatial-beta/spatialdata-visium_io.js
- packages/view-types/biomarker-select/src/BiomarkerSelectSubscriber.js
- packages/view-types/biomarker-select/src/ComparativeHeadingSubscriber.js
- packages/view-types/biomarker-select/src/SampleSetPairManagerSubscriber.js
- packages/view-types/description/src/DescriptionSubscriber.js
- packages/view-types/feature-list/src/FeatureList.js
- packages/view-types/feature-list/src/FeatureListSubscriber.js
- packages/view-types/genomic-profiles/src/GenomicProfilesSubscriber.js
- packages/view-types/genomic-profiles/src/HiGlassLazy.js
- packages/view-types/heatmap/src/HeatmapSubscriber.js
- packages/view-types/neuroglancer/src/NeuroglancerSubscriber.js
- packages/view-types/obs-sets-manager/src/ObsSetsManagerSubscriber.js
- packages/view-types/scatterplot-embedding/src/DualEmbeddingScatterplotSubscriber.js
- packages/view-types/scatterplot-embedding/src/EmbeddingScatterplotSubscriber.js
- packages/view-types/scatterplot-gating/src/GatingSubscriber.js
- packages/view-types/statistical-plots/src/CellSetCompositionBarPlotSubscriber.js
- packages/view-types/statistical-plots/src/CellSetExpressionPlotSubscriber.js
- packages/view-types/statistical-plots/src/CellSetSizesPlotSubscriber.js
- packages/view-types/statistical-plots/src/DotPlotSubscriber.js
- packages/view-types/statistical-plots/src/ExpressionHistogramSubscriber.js
- packages/view-types/statistical-plots/src/FeatureBarPlotSubscriber.js
- packages/view-types/statistical-plots/src/FeatureSetEnrichmentBarPlotSubscriber.js
- packages/view-types/statistical-plots/src/FeatureStatsTableSubscriber.js
- packages/view-types/statistical-plots/src/TreemapSubscriber.js
- packages/view-types/statistical-plots/src/VolcanoPlotSubscriber.js
- packages/view-types/status/src/StatusSubscriber.js
- scripts/create-view-template-functions.mjs
Fixes #
This is intended to prevent confusion when using linkViewsByObject (or link_views_by_dict in Python), as currently only spatialBeta/layerControllerBeta support meta=True (and the default value for `meta` is True in linkViewsByObject). After this PR, linkViewsByObject can be used with any view type, regardless of whether `meta` is True or False.
Note: In this PR i have not added support for meta-coordination in `spatial`/`layerController` as this would add extra complexity to https://github.com/vitessce/vitessce/pull/2234
-
> Meta-coordination for all views
